### ISSUE TITLE
Permission remains "always ask" after it is "granted" (on LeEco Le Max2)

### ISSUE THREAD

**Issue by Liverm0r** [tbruyelle/RxPermissions#100]
I tested two methods
`
    rxPermissions.request(Manifest.permission.CAMERA)
    rxPermissions.requestEach(Manifest.permission.CAMERA,
             Manifest.permission.READ_PHONE_STATE)`
with Camera and Location permissions on LeEco Le Max2.
In subscription I have "granted == true", but in Settings I still have permission as "Always ask" instead of "Allowed".

**Comment by tbruyelle** [comment]
"Always ask" ? Where is that setting ?

**Comment by Liverm0r** [comment]
I mean phone's general settings. I've made a screen.
http://joxi.ru/Vm6y1QdcDVlN4r

**Comment by epool** [comment]
It's weird, I haven't seen that configuration before on a device, my Nexus device doesn't have that option and I couldn't reproduce it 😞  . But if you set allowed or refused the behavior is the expected?

**Comment by Liverm0r** [comment]
Yes, If I set "allowed" or "refused" the behavior is as it should be.

**Comment by tbruyelle** [comment]
Sorry but the library won't support this kind of manufacturer custom dev.
