### ISSUE TITLE
Denied permission notification when composing with RxBindings

### ISSUE THREAD

**Issue by Orbyt** [tbruyelle/RxPermissions#103]
I have the following code that observes a button for clicks and ensures needed permissions have been granted:

```
RxView.clicks(findViewById(R.id.fabMenuFull))
                .compose(permissions.ensure(Manifest.permission.ACCESS_FINE_LOCATION))
                .subscribe(granted -> {
                    if (granted) {
                        Log.d(TAG, "granted");
                    } else {
                        Toast.makeText(this, "You wont be able to use the app without granting needed permissions.", Toast.LENGTH_SHORT).show();
                    }
                });
``` 

I'd like to be able to receive an event when the user permanently denies the permission. How can I do this?

**Comment by tbruyelle** [comment]
You have to use `ensureEach`, which provides more information. In particular it gives you the result of `shouldShowRequestPermissionRationale`.
Check the readme.
