### ISSUE TITLE
Use tags

### ISSUE THREAD

**Issue by PaulWoitaschek** [tbruyelle/RxPermissions#105]
The latest release (0.9.0) is not tagged. Can you continue adding tags and either maintaining the changelog in the releases tab or through a CHANGELOG.md file?

**Comment by PaulWoitaschek** [comment]
Also it seems the rxjava2 package is diverging and stuck at 0.8.2 while the rxjava 1 version is at 0.9.0.

**Comment by tbruyelle** [comment]
I'll add the missing tag. About the 2.x branch, @epool is working on it, thanks to him.

**Comment by PaulWoitaschek** [comment]
Why don't you just maintain the rxjava 2 version and let people use the [interop library](https://github.com/akarnokd/RxJava2Interop)?

**Comment by tbruyelle** [comment]
Cause I didn't switch to rxjava2 yet in my projects. The 2.x branch is not something I planned.
