### ISSUE TITLE
Return context-only permissions status checks

### ISSUE THREAD

**Issue by StanislavChumarin** [tbruyelle/RxPermissions#107]
There were two useful RxPermissions.isGranted and isRevoked methods that are basically just useful util wrappers around Context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED;
To use them in new 0.9.0 API Activity should be passed, but for Service this is not applicable. 
It would be useful to get those methods without Activity instance.

**Comment by tbruyelle** [comment]
Well the less ugly way would be to move that methods static...

Is it very annoying to do it yourself ?

```java
Observable.just( Context.checkSelfPermission(p) == PackageManager.PERMISSION_GRANTED ) 
```

**Comment by StanislavChumarin** [comment]
That is not hard, but having all done in one place is preferable way - library that states for rxfying permissions. 
This is my suggestion for the improvement. I can try to create Pull Request for it.

**Comment by tbruyelle** [comment]
Ok, I'll wait your PR to see.
