### ISSUE TITLE
RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

### ISSUE THREAD

**Issue by wlrnet** [tbruyelle/RxPermissions#108]
I found some issue in online user, they crashed when reqeust permissions.

Exception java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.sss.mobile.android.ssss/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
android.app.ActivityThread.deliverResults (ActivityThread.java:3699)
android.app.ActivityThread.handleSendResult (ActivityThread.java:3742)
android.app.ActivityThread.access$1400 (ActivityThread.java:150)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1393)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:171)
android.app.ActivityThread.main (ActivityThread.java:5417)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Caused by java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult (RxPermissions.java:286)
com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult (ShadowActivity.java:32)
android.app.Activity.dispatchRequestPermissionsResult (Activity.java:6616)
android.app.Activity.dispatchActivityResult (Activity.java:6494)
android.app.ActivityThread.deliverResults (ActivityThread.java:3695)
android.app.ActivityThread.handleSendResult (ActivityThread.java:3742)
android.app.ActivityThread.access$1400 (ActivityThread.java:150)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1393)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:171)
android.app.ActivityThread.main (ActivityThread.java:5417)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Manufacturer: ZTE
Model: Z981
Board: Urd
Android API: 23
Android OS: 6.0.1
Brand: Zte
RAM: 1.8GB
Available on disk: —
Orientation: Portrait
Proximity to user: —

**Comment by tbruyelle** [comment]
Version 0.9.1 fixes that exception.
