### ISSUE TITLE
Avoid ask others permission if one is not granted

### ISSUE THREAD

**Issue by agustinsivoplas** [tbruyelle/RxPermissions#109]
I want to avoid ask others permission if the user not grant one.

For example: I ask for read/write external storage and camera, if the user deny the first, the library ask for camera permission.

```
RxPermissions.getInstance(getActivity()).request(Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.CAMERA)
                .subscribe(granted -> {
                    if (granted) {
                       dispatchCamera();
                    } else {
                        showError();
                    }
                });
```

I think I could use requestEach, but I dont know how stop to emit items if one permission is not granted and also I cant obtain the final result, if the user grant all permissions.

**Comment by PaulWoitaschek** [comment]
Use the existing RxJava operators.

```java
rxPermissions.request(WRITE_EXTERNAL)
  .filter(granted -> granted)
  .flatMap(ignore -> rxPermissions.request(CAMERA)
  .filter(granted -> granted)
  ...
```

**Comment by agustinsivoplas** [comment]
The solution I was searching was somethig like this:

> RxPermissions
>       .getInstance(getActivity())
>       .requestEach(Manifest.permission.WRITE_EXTERNAL_STORAGE, 
>          Manifest.permission.READ_EXTERNAL_STORAGE, 
>          Manifest.permission.CAMERA)
>       .takeWhile(permission -> permission.granted)
>       //or use take untill if you want to get permission.granted == false event
>       //.takeUntil(permission -> !permission.granted)
>       .subscribe(granted -> {
>         if (granted) {
>            dispatchCamera();
>         } else {
>            showError();
>         }
>       });
