### ISSUE TITLE
get final user's response in case of multiple permissions!

### ISSUE THREAD

**Issue by khaledkhj** [tbruyelle/RxPermissions#117]
When requesting for multiple permissions, we gonna have 2 Permission objects, meaning that "call mehtod" will be called twice!

Is there any way to avoid this, I mean how to decide that we got all the permissions granted at once without going twice into call method?

rxPermissions.requestEach(Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .subscribe(new Action1<Permission>() {
                    @Override
                    public void call(Permission permission) {
                        if (permission.granted) {

                        } else if (permission.shouldShowRequestPermissionRationale) {
                            // Denied permission without ask never again
                            ToastHelper.show(getApplicationContext(), "Denied permission without ask never again");
                        } else {
                            // Denied permission with ask never again
                            // Need to go to the settings
                            ToastHelper.show(getApplicationContext(), getString(R.string.msg_storage_permission));
                        }
                    }
                });

Thank you.

**Comment by tbruyelle** [comment]
Try `rxPermissions.request((Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE)`

**Comment by khaledkhj** [comment]
Yes That is what I was looking for.

Thank you @tbruyelle
