### ISSUE TITLE
shouldShowRequestPermissionRationale without Activity

### ISSUE THREAD

**Issue by AlimovAndrey** [tbruyelle/RxPermissions#120]
Thomas, thank you for incredible lib.

I need show dialog with explaining for user why asked permissions. So I want get shouldShowRequestPermissionRationale in first and then or show dialog or skip. And that all in my Presenter...

There question is, can I get shouldShowRequestPermissionRationale without Activity?

I finded only below code:
`@SuppressWarnings("WeakerAccess")
public Observable<Boolean> shouldShowRequestPermissionRationale(final Activity activity, final String... permissions) {
        if (!isMarshmallow()) {
            return Observable.just(false);
        }
        return Observable.just(shouldShowRequestPermissionRationaleImplementation(activity, permissions));
    }`

**Comment by tbruyelle** [comment]
No you can't, `shouldShowRequestPermissionRationale` is an `Activity` method.
