### ISSUE TITLE
Recursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by myhcqgithub** [tbruyelle/RxPermissions#127]
Hello , I  used   to throw in fragment  ` java.lang.IllegalStateException: Recursive entry to executePendingTransactions `
Look forward to reply~

**Comment by mrArtCore** [comment]
Hello, how about more information?

**Comment by myhcqgithub** [comment]
resolved thanks!

**Comment by kjsolo** [comment]
@myhcqgithub How to solve?
