### ISSUE TITLE
程序崩溃-ShadowActivity 我使用的版本是0.7.0

### ISSUE THREAD

**Issue by renjinlong** [tbruyelle/RxPermissions#129]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.cashpie.loan/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
	android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
	android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
	android.app.ActivityThread.-wrap22(ActivityThread.java)
	android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
	android.os.Handler.dispatchMessage(Handler.java:102)
	android.os.Looper.loop(Looper.java:156)
	android.app.ActivityThread.main(ActivityThread.java:6524)
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by : java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

**Comment by mrArtCore** [comment]
https://github.com/tbruyelle/RxPermissions/issues/106
Please, do some research before copy paste stacktrace.
