### ISSUE TITLE
Hashcode of Permission Object

### ISSUE THREAD

**Issue by andretietz** [tbruyelle/RxPermissions#13]
The Hashcode of the Permission Object returns either 0 or 31

See:
https://github.com/tbruyelle/RxPermissions/blob/master/lib/src/main/java/com/tbruyelle/rxpermissions/Permission.java#L26

**Comment by andretietz** [comment]
sorry

**Comment by tbruyelle** [comment]
This is code generated by Android Studio, I hope it's correct :D

**Comment by andretietz** [comment]
Yeah, sorry, sometimes my eyes play with me..., havn't seen the "result" variable after the 31 :D
