### ISSUE TITLE
Is RxPermissions  can  use  in  Fragment

### ISSUE THREAD

**Issue by naivor** [tbruyelle/RxPermissions#130]
When i use  RxPermissions  in Fragment,i get a  exception,  the log is
`
rx.exceptions.OnErrorNotImplementedException: xxx
`

Is RxPermissions  can  only use  in  Activity?

**Comment by tbruyelle** [comment]
No you can use it in a fragment. Write the error handler to catch the
exception and report it please.

**Comment by naivor** [comment]
oh,the RxPermission is ok,it's mine  fault .I spent  severial hours and  found that error occoured in the block after  the  permission  granted,but  the  exception was  captured by  RxPermission.  Thanks !

**Comment by Sugarya** [comment]
Does it support to callback onActivityResult in Fragment ? @tbruyelle
