### ISSUE TITLE
BuildConfig conflict

### ISSUE THREAD

**Issue by hsiunien** [tbruyelle/RxPermissions#131]
we use a android library(thirdpard sdk ) imported rxpermissions version 0.7,and i use rxpermissions 0.9.3 and when i compile ,android show me the error that conflict with BuildConfig and i found 0.9.3 contain the same class with 0.7 is com.tbruyelle.rxpermissions.BuildConfig ,i don't know how to exclude BuildConfig in library ,if i exclude the module rxpermissions in library,it will crash when library using rxpermissions method. could you don't package BuildConfig.class if it needn't.

**Comment by tbruyelle** [comment]
You should force the version 0.9.3 for the library.

**Comment by hsiunien** [comment]
i can't modify library code, how to force the version 0.9.3 for the library safetly?   0.7 is using rxjava1.x, if i force use 0.9.3 ,it cannot find com.tbruyelle.rxpermissions.Permission

**Comment by tbruyelle** [comment]
There's possibly a breaking changes between 0.7 and 0.9.3. You have no other choice than trying  to update the library code.

**Comment by hsiunien** [comment]
i think you shouldn't package BuildConfig.java in 0.9.3 or later,is it necessary? or you can rename package of  BuildConfig.java to com.tbruyelle.rxpermissions2.

 
<img width="1482" alt="qq20170406-155132 2x" src="https://cloud.githubusercontent.com/assets/5487535/24743546/37bf9c6e-1ae1-11e7-8f03-c78bcbe99442.png">

**Comment by iffanmajid** [comment]
I have this issue too, how to solve it btw? @hsiunien

**Comment by hsiunien** [comment]
@iffanmajid  I copied the source code in to my project and removed the BuildConfig 😄

**Comment by MugWorld** [comment]
@hsiunien it is not elegant~~........
