### ISSUE TITLE
Can not DownLoad Lib

### ISSUE THREAD

**Issue by carl1990** [tbruyelle/RxPermissions#134]
in my `android lib project` gradle.build file ,I set ` compile "com.tbruyelle.rxpermissions:rxpermissions:0.9.3@aar" ` and `jcenter()`config and then build project.
but get error with info 
   > Could not resolve all dependencies for configuration 
  :_debugPublishCopy'.
   > Could not find com.tbruyelle.rxpermissions2:rxpermissions:0.9.3.
     Required by:
         project :

**Comment by tbruyelle** [comment]
The lib is there https://bintray.com/tbruyelle/tbruyelle/RxPermissions2/0.9.3, maybe jcenter had connectivity issues during your attempt. Please try again and let me know.
