### ISSUE TITLE
Wrong behavior after screen rotation

### ISSUE THREAD

**Issue by alexey-rabets** [tbruyelle/RxPermissions#136]
In my app I have 2 buttons in one screen which both require READ_EXTERNAL_STORAGE permission. If I rotate a screen while a permission dialog is displayed, then after clicking Allow button both button click listeners are fired. I have forked the repositiory and modified the sample to demonstrate this issue:

https://github.com/alexey-rabets/RxPermissions

Steps to reproduce:
1. Launch the sample.
2. Click on Button 1 -> Permission dialog is displayed (don't click Deny or Allow).
3. Rotate the screen.
4. Click Allow button.
5. Toast "Button 1 clicked" is displayed 2 times, toast "Button 2 clicked" is displayed 1 time. We should have toast "Button 1 clicked" displayed 1 time only.

**Comment by mrArtCore** [comment]
@alexey-rabets 
Hello, so you think it is bug ?
But I dont think so. 
Your code is uncorrect. If you dont want your listeners being invoked twice or more, you MUST unsubscrbe from them in, for instance, `onDestroy()` activity callback.

In your current realization I have seen that you're subscribing to different observables, giving references to your UI elements and activity. But, as you probably know, after screen roation, activity destroys and recreates. And in your realization it couldn't be destroyed, cause your have references to activity in RxJavaEnviroment. So after rotation you have 1 activity in memory and another one that rectreates. 
And all callbacks such as `onCreate(...), onStart() etc` are called again. And you again subscribe to all rx stuff and give away references to new Activity )))
So you have now 2 (or more, depend of how many times you rotate phone) references to your activity after screen rotation and memory leak =)) lol =)

How to fix:
add all `Subscriptions` to `CompositeSubscription` and in some Activity's callback like `(onPause())` call `compositeSubscription.clear()`. Those magic things unsubscribe all your listeners and avoid memory leaks and multiple _firing_ of `subscribe()` method

**Comment by alexey-rabets** [comment]
Understood. Thanks.
