### ISSUE TITLE
hello,tbruyelle. I hvae a problem ,if the user select the" never ask again" and deny the permission,how can i know that

### ISSUE THREAD

**Issue by designerMichael** [tbruyelle/RxPermissions#137]
hello,tbruyelle. I hvae a problem ,if the user select the" never ask again" and deny the permission,how can i know that?

**Comment by tbruyelle** [comment]
It's in the README, use `requestEach/ensureEach` to have a detailled object of what happened during the permission request.

**Comment by designerMichael** [comment]
thanks very much, I Have test the code ,and get the result if the user select the "never ask again", so I use the rxPermission to get permission again ,but no permission dialog to show, is there another way to do with  this?

**Comment by tbruyelle** [comment]
This is the normal behavior. If the user has clicked "never ask again" and if the permission is critical for your app, you have to invite the user to go to the settings and to change manually the permissions of your app. There's no other alternatives.

**Comment by designerMichael** [comment]
thank you for your help! ^_^
