### ISSUE TITLE
Calling compose&subscribe within onActivityCreated in fragment leads to crash

### ISSUE THREAD

**Issue by MinkiPan** [tbruyelle/RxPermissions#140]
```
onActivityCreated {
RxView.clicks(btn_fragment_permissions_camera)
				.compose(rxPermissions.ensure(Manifest.permission.CAMERA))
				.filter { it }
				.subscribe {
					Toast.makeText(activity, "Camera Permission granted", Toast.LENGTH_SHORT).show()
				} 
}
```

> java.lang.IllegalStateException: Recursive entry to executePendingTransactions
>                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1550)
>                                                                                     at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
>                                                                                     at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:54)
>                                                                                     at com.tbruyelle.rxpermissions2.RxPermissions.<init>(RxPermissions.java:41)
>                                                                                     at com.example.mingkangpan.learnrx2.fragment.PermissionFragment$rxPermissions$2.invoke(PermissionFragment.kt:21)
>                                                                                     at com.example.mingkangpan.learnrx2.fragment.PermissionFragment$rxPermissions$2.invoke(PermissionFragment.kt:19)
>                                                                                     at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
>                                                                                     at com.example.mingkangpan.learnrx2.fragment.PermissionFragment.getRxPermissions(PermissionFragment.kt:0)
>                                                                                     at com.example.mingkangpan.learnrx2.fragment.PermissionFragment.init(PermissionFragment.kt:35)
>                                                                                     at com.example.mingkangpan.learnrx2.fragment.PermissionFragment.onActivityCreated(PermissionFragment.kt:30)
>                                                                                     at android.app.Fragment.performActivityCreated(Fragment.java:2361)

when I use rxpermissions in fragment, I cant use it in onActivity create, seems like the fragment manager is in same state while onActivityCreated, which doesn't allow another fragment to be attached

**Comment by tbruyelle** [comment]
Fragments are really a plague !

**Comment by MinkiPan** [comment]
do you think this is somehow fixable? meanwhile I have to post delay the method call

**Comment by tbruyelle** [comment]
Sorry I have no idea, community pushed me to use fragments for this lib (originally it was an Activity), and I finally accepted but I regret. I don't use fragment from ages, so sorry I can't help you.

**Comment by epool** [comment]
@MinkiPan could you please share us a project example to reproduce this error?

**Comment by MinkiPan** [comment]
@epool 
`	override fun onActivityCreated(savedInstanceState: Bundle?) {
		super.onActivityCreated(savedInstanceState)

		RxView.clicks(btn_fragment_permissions_camera)
				.compose(rxPermissions.ensure(Manifest.permission.CAMERA))
				.filter { it }
				.subscribe {
					Toast.makeText(activity, "Camera Permission granted", Toast.LENGTH_SHORT).show()
				}
	}`

this is the code which leads to crash
