### ISSUE TITLE
In XiaoMi5 ,Android 7.0,Rxpermission0.9.4 always return true

### ISSUE THREAD

**Issue by hedahuan** [tbruyelle/RxPermissions#142]
As the title said,whenever I turn off the permission ,it always return true
Here's my code.
` RxPermissions rxPermissions = new RxPermissions(this);
        rxPermissions.request(Manifest.permission.READ_CONTACTS)
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean aBoolean) {
                        Log.d("permission", "--" + aBoolean);
                    }
                });
`

**Comment by tbruyelle** [comment]
This lib doesn't handle Xiaomi specific permission system.

**Comment by windows771053651** [comment]
这表明小米系统改了权限模块
