### ISSUE TITLE
extend approach to support OnActivityResult

### ISSUE THREAD

**Issue by andaag** [tbruyelle/RxPermissions#15]
Should probably be as a seperate library/maybe base library that this one also uses.

Dealing with OnActivityResult is a trickier case.

Example scenario:
1. User clicks on "get google login token" button.
2. Play services isn't updated -> out of app -> OnActivityResult (.. not even sure you get an OnActivityResult here actually.. Would need to recheck this in onResume...)
3. User needs to select account -> out of app -> OnActivityResult
4. User needs to authorize the scopes -> out of app -> OnActivityResult
5. Now we have a valid google client, and need to trigger get token (on another thread).

For most of them I think we could just restart the entire flow (running the code again will just skip that step anyway). In order to trigger any action you'll need to get a valid googleApiClient, which is also an async request.

Lets say each request has an identifier. We would have to store all OnActivityResult results to SavedInstanceState as long as that identifier isn't completed/unsubscribed. That way when for example 3-SelectUserAccountOperator runs it'll check if we already have a result, if we do we can just passthrough.

**Comment by andaag** [comment]
Might not need to share much code really... The only thing would be the shadow activity, and that isn't much to just duplicate :p

**Comment by tbruyelle** [comment]
The goal of `RxPermissions` is not to handle `onActivityResult`. Maybe you could create an other library for that.
