### ISSUE TITLE
rxjava2 RxPermissions0.9.4  find the problem

### ISSUE THREAD

**Issue by yzcheng90** [tbruyelle/RxPermissions#150]
hello ,my device android 7.0 
show code:
new RxPermissions(this).request(
                                Manifest.permission.CAMERA,
                                Manifest.permission.RECORD_AUDIO,
                                Manifest.permission.WRITE_EXTERNAL_STORAGE).subscribe((Boolean aBoolean) ->{
                                if (aBoolean) { 
                                   
                                } else {
                                  
                                }
                        });

These permissions are allowed,why aBoolean return false

**Comment by ck227** [comment]
same issue here.

**Comment by DroidNinja** [comment]
same issue here.

**Comment by mrArtCore** [comment]
Hello guys! @DroidNinja @ck227 @yzcheng90 
Could you please provide more information about your problem ? In ideal test project, where this problem can be recreated by somebody else ???
And there is no full information about Device ! You are developers, and my device is Android 7.0.0 it is not description from developer. That description could give my grandma, for example. 
Device Brand. Manufacture, Build №, etc will be brilliant ! 

How you create and manage RxPermission ? Where are you do so? How are you manage lifecycle and permisisons request? Frequency of issue ?

Of, course If you interested in fix of this problem. 
Thanks !

**Comment by DroidNinja** [comment]
Okk I got the fix. My issue was due to not including the required permission in manifest file. 
Anyway thanks!

**Comment by maxxx** [comment]
Confirm same issue with Manifest.permission.WRITE_SETTINGS (defind in manifest also). There is https://github.com/tbruyelle/RxPermissions/issues/51 but it's useless, so let's try again.
my test code inside of onCreate in activity:

```
		new RxPermissions(this)
				.requestEach(Manifest.permission.CHANGE_NETWORK_STATE, Manifest.permission.WRITE_SETTINGS, Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION)
				.subscribe(permission -> {
					if (permission.granted) {
						// granted
					} else {
						Toast.makeText(this, "You must allow required permissions", Toast.LENGTH_LONG).show();
					}
				});
```
tested on android emulators - api 23/24 and on asus zenfone max 3 api 24

**Comment by liwentao19881010** [comment]
I met the same problem,at last,i found that i did not request permission in Manifest.When id requested the permission in manifest, it work well.
