### ISSUE TITLE
No Callback on Samsung Galaxy S7

### ISSUE THREAD

**Issue by lopspower** [tbruyelle/RxPermissions#153]
I have a Samsung Galaxy S7 on Android 6.0.1.

When I call the permission for the first time and validate it, I don't have callback:

```
new RxPermissions(this).request(Manifest.permission.READ_PHONE_STATE)
                .subscribe(granted -> {
                    // No call back here after validation of the permission
                });
```

This same code works well on other devices, I do not understand.

**Comment by tbruyelle** [comment]
Why do you have a Samsung you're a developer isn't it ? xD

**Comment by lopspower** [comment]
Ahaha ^^. Personally I would be glad if there was no Samsung.. But the applications I develop are not just for me.

More seriously, the bug is strange since [the classic implementation of the management of the permissions](https://developer.android.com/training/permissions/requesting.html) works well on this device. I think the problem comes from the library and not from the device.

**Comment by tbruyelle** [comment]
Yes that's strange, it's the first time someone raise me this kind of issue. I don't think it's the first time the library is used on a S7.

This only occurs the first time you request the permission ?

**Comment by lopspower** [comment]
That's it. When permission is accepted and I make the request I have the true callback. I have been using your library for a while this is the first time I have a problem like this.
If you need to do a test on an S7 do not hesitate.

**Comment by tbruyelle** [comment]
So it's when the dialog appears, maybe Samsung broke something in the lifecycle during this process.
Are you sure you perform the `request` in an initialization phase ?

**Comment by lopspower** [comment]
I run the request after clicking a button. This same code works well on all other devices. And this same code works fine if I restart the app and the permission is already validated.

**Comment by tbruyelle** [comment]
Do you request inside a click listener ? If yes it's not an initialization phase and you will have the same problem on any device if you rotate the screen while the permission dialog is shown.

Try to follow the example in the README : 

```java
// Must be done during an initialization phase like onCreate
RxView.clicks(findViewById(R.id.enableCamera))
    .compose(rxPermissions.ensure(Manifest.permission.CAMERA))
    .subscribe( ... )
```

**Comment by tbruyelle** [comment]
@lopspower so did you fix the issue with my last comment ?

**Comment by lizwangying** [comment]
Looks like you have to borrow a S7 and see~ @tbruyelle 😄
