### ISSUE TITLE
小米4手机禁用权限后，下载点击不在弹出提示信息，三星note5可以

### ISSUE THREAD

**Issue by shiyd0516** [tbruyelle/RxPermissions#154]
小米4手机禁用权限后，下载点击不在弹出提示信息，三星note5可以

**Comment by mrArtCore** [comment]
Lol

**Comment by tbruyelle** [comment]
Gne

**Comment by gengjiawen** [comment]
So many rom manufacters provide an option for users to `ignore the same permission request`, this will result in endless cycle. I fix the problem using the system permission with an boolean value to prevent repeat dialog show.

**Comment by gengjiawen** [comment]
In short, it can result in keep calling `onRequestPermissionsResult`.

**Comment by mrArtCore** [comment]
@gengjiawen 
You answered to question of this issue? Could you please translate the original text? What I could understand that was something wrong with note5 ☺️
