### ISSUE TITLE
support for rxjava2.0.1

### ISSUE THREAD

**Issue by prazjain** [tbruyelle/RxPermissions#163]
Hi,
I get compilation error when I try to do this:
rxPermission.request(Manifest.permission.READ_CONTACTS)
     .observeOn(AndroidSchedulers.mainThread())
    .subscribe(granted -> ......);

The error is on observeOn line, saying : 
Error:(177, 56) error: incompatible types: io.reactivex.Scheduler cannot be converted to rx.Scheduler

**Comment by mrArtCore** [comment]
Hi
Maybe you should to read error carefully ??? Looks like you using RxJava1 and Rxjava2 in the project. And at line (177, 56) you try to use rx.Scheduler instead of  io.reactivex.Scheduler ???

**Comment by prazjain** [comment]
my project is using: 
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.0.1'

When I look at build.gradle for rxpermissions then I see this : 
rxJava = 'io.reactivex:rxjava:1.2.9'

**Comment by mrArtCore** [comment]
And what is the version of this library do you use? And why don't you use version with Rx java2 support? Check out main page of the project

**Comment by prazjain** [comment]
I am using this : 
'com.tbruyelle.rxpermissions:rxpermissions:0.9.4@aar'

I have just noticed there is a rxjava2 support version as well :
'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'

I will give it a try tonight.

**Comment by prazjain** [comment]
I think the problem here is that RxPermissions.request(...) method is returning a Observable from rxjava-1.1.6, and thats why chained observeOn method which passes AndroidScheduler.mainThread() is not compatible with that object

**Comment by mrArtCore** [comment]
@prazjain 
You just use wrong scheduler with whatever RxPermission instance version you have. 
Profile your imports, dependencies and use correct versions of RxJava and RxAndroid.

BTW, there is no Observable from rxjava-1.1.6 In "com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar" dependency. You doing something wrong. Library works fine !
