### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by dsaff** [tbruyelle/RxPermissions#168]
There appears to be a LICENSE file, but not a copyright statement about who is assert the right to license the code.  (for example, see the bottom of https://github.com/JakeWharton/RxBinding/blob/master/README.md)

Did I miss something?

**Comment by tbruyelle** [comment]
I don't know is this required for APACHE2 license ?

**Comment by nmulcahey** [comment]
Yes, there are instructions here: https://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by tbruyelle** [comment]
@dsaff @nmulcahey thank you guys, I've just added it to the README.
