### ISSUE TITLE
targetsdk pre 23

### ISSUE THREAD

**Issue by keremcomak** [tbruyelle/RxPermissions#17]
Does it have to be the target SDK 23?

I want  all permissions to be granted and  I want to see permission dialog if user has already denied permission

**Comment by tbruyelle** [comment]
No, the `minSdkVersion` to use this library is 9

I will add that in the README.

**Comment by keremcomak** [comment]
Please check it.
 
mCtx.checkSelfPermission(permission) always return 0 when I set targetSdk 22

**Comment by tbruyelle** [comment]
What do you want me to check ? `mCtx.checkSelfPermission(permission)` is not even a call to this library.

**Comment by keremcomak** [comment]
```
@TargetApi(Build.VERSION_CODES.M)
    private boolean hasPermission_(String... permissions) {
        for (String permission : permissions) {
            if (mCtx.checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED) {
                return false;
            }
        }
        return true;
    }
```

in RxPermissions.java

**Comment by tbruyelle** [comment]
I know I use it.
The method `hasPermission_` is only called if current sdk is >=23.

**Comment by keremcomak** [comment]
(compileSdk 23) current sdk 23 (nexus5 android 6.0) but targetSdk 18 in gradle and ```hasPermission_``` is always return 0.

if targetSdk is not 23, permissions dialog is always not showing .

I will update my app and Do I have to set targetSdk 23. I want to still granted permissions.

**Comment by tbruyelle** [comment]
> if targetSdk is not 23, permissions dialog is always not showing .

Fair enough since runtime permissions are only available for target 23.
