### ISSUE TITLE
Lambda expressions are not supported at this language level

### ISSUE THREAD

**Issue by hw20101101** [tbruyelle/RxPermissions#170]
![image](https://user-images.githubusercontent.com/9107226/29454675-9e2a55a2-8440-11e7-9922-ef5e07ec6482.png)

build.gradle : 
```
//权限管理
    //compile "io.reactivex.rxjava2:rxjava:2.1.3"
    compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.3'
```

**Comment by mrArtCore** [comment]
Just google it, man. This is not an issue of library!
