### ISSUE TITLE
xiaomi6(MiUI) mobile phone permission

### ISSUE THREAD

**Issue by windows771053651** [tbruyelle/RxPermissions#171]
I request permission in onResume()，then I reject the pemission。Then onResume() and onPause() start an infinite loop.
This is my code:

@Override
    protected void onResume() {
        super.onResume();
        LogUtil.error(getClass(), "onResume");
        String[] permissions = {
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.READ_EXTERNAL_STORAGE};
        RxPermissionsUtil.getRxPermissions(this).request(permissions).subscribe(new BaseObserver<Boolean>() {
            @Override
            public void onNext(Boolean value) {
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        LogUtil.error(getClass(), "onPause");
    }

**Comment by tbruyelle** [comment]
Dup of #142

**Comment by mrArtCore** [comment]
I think problem could be in wrong logic of invocation permissions request regards to lifecycle. When dialog shows, onPause() called. Than dialog canceled, called onResume(), than permission requested one more time and so on. This not an issue of lib, this problem of programmer. 
You should Request permission in onCreate for example, and all will be ok, I suppose
