### ISSUE TITLE
Add internal tracker to see if permission has been asked for before.

### ISSUE THREAD

**Issue by sbaar** [tbruyelle/RxPermissions#172]
A limitation of the should shouldShowRequestPermissionRationale field is that if the user checks "dont ask me again", then shouldShowRequestPermissionRationale is false, which precludes that fields use as a proxy for "have I asked for this before"

Basically, myself and I assume others would like to make a distiniction between "first time I've asked, first rejection" and "nth time I've asked, nth rejection, with "don't ask me again". For example, the first time I ask for a permission during on boarding I may want to skip showing the rationale, but later I may want to ask for it again and show the rationale, even if the user said "don't ask me again"

Since the RxPermissions() object takes an activity, I propose saving the history of asking in shared preferences and exposing it in the permissions object returned in requestEach. Would a PR be welcome?

**Comment by tbruyelle** [comment]
No, I don't want to add complex features like that.
