### ISSUE TITLE
Add support for message to show when requesting permission grant

### ISSUE THREAD

**Issue by MKevin3** [tbruyelle/RxPermissions#175]
When I request a permission I don't always use the generic prompt. I may need to say something like "Our app needs to have the camera permission to scan UPC codes". The Android SDK supports providing a "why I want it" string and I would like to see it added to this library.

**Comment by tbruyelle** [comment]
Is it something new ? Can you link me the doc please ?

**Comment by MKevin3** [comment]
Handling this:
shouldShowRequestPermissionRationale()

See the docs here
https://developer.android.com/training/permissions/requesting.html

**Comment by tbruyelle** [comment]
Ok there's nothing new, the lib already handles `shouldShowRequestPermissionRationale`.
