### ISSUE TITLE
About "Need to go to the settings" condition ...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tbruyelle/RxPermissions#179]
The example shows this:

```
                                   else {
                                       // Denied permission with ask never again
                                       // Need to go to the settings
                                       Toast.makeText(MainActivity.this,
                                               "Permission denied, can't enable the camera",
                                               Toast.LENGTH_SHORT).show();
                                   }
```

To do it, I can call this:
```

    fun prepareAppDetailsIntent(context: Context): Intent {
        val packageName = context.packageName
        val packageURI = Uri.parse("package:" + packageName)
        return Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, packageURI)
    }

startActivityForResult(prepareAppDetailsIntent(this),REQUEST_ID__SETTINGS)
```

But then how can the library handle it? I need to have "onActivityResult" being added this way, no?

**Comment by tbruyelle** [comment]
The library won't handle it.

**Comment by AndroidDeveloperLB** [comment]
So how should we do it?
The only solution I can think of, is to create a function "onPermissionsGranted", that will be called in both "onActivityResult" (after it checks for permissions again) and here:

```
rxPermissions
    .requestEach(...)
    .subscribe(permission -> { 
        if (permission.granted) {
            onPermissionsGranted
        } else ...
    });
```

Can you please recommend of what's the best way to handle this?

**Comment by MNGsulochana** [comment]
Intent myAppSettings = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.parse("package:" + getPackageName()));
startActivityForResult(myAppSettings, REQUEST_APP_SETTINGS);

********************************************************************************88
I am also trying to call the application settings activiyt like this,but from the onActiviytresult I am getting the result as "0" for this Intent.
May I know y?????
