### ISSUE TITLE
dialog is not appear

### ISSUE THREAD

**Issue by hienhtet** [tbruyelle/RxPermissions#180]
request permission dialog is not appear in activity bro
i defined like this 

 rxPermissions = RxPermissions.getInstance(this);
        rxPermissions
                .request(Manifest.permission.CAMERA,
                        Manifest.permission.READ_PHONE_STATE,
                        Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_SETTINGS)
                .subscribe(granted -> {
                    if (granted) {
                        grantedAll = true;
                    } else {
                        grantedAll = true;
                    }
                });

**Comment by tbruyelle** [comment]
There's no such bug in the library.
Dont forget to declare the permissions in your manifest.
