### ISSUE TITLE
App crash after grant permission

### ISSUE THREAD

**Issue by DanteAndroid** [tbruyelle/RxPermissions#189]
log(not sure comes from my app coz the app just crash):
```
11-20 17:14:15.622 3701-3711/? E/System: Uncaught exception thrown by finalizer
11-20 17:14:15.622 3701-3711/? E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.qualcomm.qti.Performance.native_deinit() (tried Java_com_qualcomm_qti_Performance_native_1deinit and Java_com_qualcomm_qti_Performance_native_1deinit__)
                                             at com.qualcomm.qti.Performance.native_deinit(Native Method)
                                             at com.qualcomm.qti.Performance.finalize(Performance.java:263)
                                             at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                             at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                             at java.lang.Thread.run(Thread.java:762)
```

Code:
```
    private void save(final Bitmap bitmap) {
//    private ViewerActivity context; here is in fragment, context is activity
        RxPermissions permissions = new RxPermissions(context);
        Subscription subscription = permissions.request(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .compose(applySchedulers())
                .subscribe(granted -> {
                    if (granted) {
                        if (BitmapUtil.writeToFile(bitmap).exists()) {                        
                           //ui hint
                        } else {
                          //ui hint
                        }
                    }
                });
        tasks.add(subscription);
    }
```
Phone:
Samsung G550 
(In Emulator is OK)

**Comment by mrArtCore** [comment]
Why do you  think this lib is guilty in crash? Did you even try to figure out whats went wrong ? I think you  have to learn read logs. And learn to google. Googling in the right way might be very helpfull in our deal.

**Comment by diklimchuk** [comment]
I had the same issue. Fixed it with `System.loadLibrary("my_lib_name")`. Not sure why this is necessary though.

**Comment by DanteAndroid** [comment]
@mrArtCore well, I think you're right cause this crash only happens in Samsung phones. BTW, I had tried googled it but find nothing.

**Comment by mrArtCore** [comment]
Hey @DanteAndroid 
First of all we need to see more code, then just 1 function without other context. Maybe it called after onDestroy() or something like that ??? 
Then about crash log. It clearly describe what had been happened with **java.lang.UnsatisfiedLinkError.**
It is key for problem solving. As I remember this error appears in most cases when your code  couldn't find path to JNI lib classes. Or when JNI lib couldn't be loaded. Try to google about **java.lang.UnsatisfiedLinkError** 
Does your app use some native libs ???

Also you could start from [here](https://docs.oracle.com/javase/7/docs/api/java/lang/UnsatisfiedLinkError.html) and maybe [here](https://examples.javacodegeeks.com/java-basics/exceptions/java-lang-unsatisfiedlinkerror-how-to-handle-unsatisfied-link-error/)

**Comment by DanteAndroid** [comment]
That's nice of you. Since I don't own that Samsung device now, I'll close this issue. I'll check out your link, thanks again!

**Comment by tim12332000** [comment]
@DanteAndroid Did you fix the problem ??
