### ISSUE TITLE
Support @RequiresPermission lint

### ISSUE THREAD

**Issue by vanniktech** [tbruyelle/RxPermissions#19]
Are there any plans on supporting @RequiresPermission? For instance I have the following code

```java
final Observable<Void> trigger = RxView.clicks(fab);
rxPermissions.request(trigger, Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE).subscribe(granted -> {
    if (granted) {
        takePicture();
    } else {
        final View rootView = findViewById(R.id.coordinator_layout);
        Snackbar.make(rootView, R.string.permission_denied, Snackbar.LENGTH_LONG).show();
    }
}, t -> VNTLog.e("Activity", t));
```

and takePicture looks like this:

```java
@RequiresPermission(allOf = { Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA })
private void takePicture() {
// Some code
}
```

I get an error saying that I should check the permissions when I call takePicture. I'm not even sure whether there is actually a way of fixing that from your side (the library) since you'll call checkPermission. I just want to point it out however.

**Comment by tbruyelle** [comment]
Interesting. The document I found [1] on `@RequiresPermission` doesn't tell how it works, so I can't figure out how to handle that.

I'll try to look further.

[1] http://tools.android.com/tech-docs/support-annotations

**Comment by vanniktech** [comment]
Yeah I don't know it either. I know that I could disable the check with

```java
// noinspection ResourceType
takePicture();
```

**Comment by vanniktech** [comment]
@tbruyelle anything you found out on this one? I guess the lib itself can't really do much in this case.

**Comment by tbruyelle** [comment]
No sorry, I didn't.

**Comment by vanniktech** [comment]
Then let's leave it and close this one.
