### ISSUE TITLE
request multiple permissions  return not one result

### ISSUE THREAD

**Issue by a1018875550** [tbruyelle/RxPermissions#195]
I'm use requestEach to request multiple permissions.But I get more than one result. the result size is the request permission count? why

**Comment by mrArtCore** [comment]
`requestEach()` will trigger `subscribe()` as many times as many permission you are requesting.  So if you want request multiple permissions and get notified only once use `request()` method.

**Comment by AleksanderMielczarek** [comment]
Look at #197

**Comment by tbruyelle** [comment]
#197 is merged and shipped in `0.9.5`
