### ISSUE TITLE
怎么获取当前正在申请什么权限

### ISSUE THREAD

**Issue by lovechenghao** [tbruyelle/RxPermissions#198]
我需要在用户提示拒绝后，弹出提醒，但怎么获取当前正在申请什么权限？

**Comment by zhangle1024** [comment]
批量获取用户权限有两个方法，分别是rxPermission.request()和rxPermission.requestEach()，前者可以得到权限是否已经全部授予，后者可以逐个校验当前正在处理哪个授权，当前权限是否已同意。

**Comment by ewoks** [comment]
You request it next time you need it, not before. 

p.s. Please write in English so everyone (including maintainer) can understand and you increase chances your issue will not be ignored

**Comment by ewoks** [comment]
@tbruyelle should be closed
