### ISSUE TITLE
怎么判断所有权限是否申请完成

### ISSUE THREAD

**Issue by fastenCh** [tbruyelle/RxPermissions#199]
怎么以此判断所有权限是否都申请成功

**Comment by zhangle1024** [comment]
rxPermission.request()和rxPermission.requestEach()，前者可以得到所有权限是否已经申请成功，后者可以监听每个权限的申请状态！

**Comment by ewoks** [comment]
Please write in English so everyone (including maintainer) can understand and you increase chances your issue will not be ignored

**Comment by ewoks** [comment]
@tbruyelle should be closed

**Comment by tbruyelle** [comment]
Please write the issue in english.
