### ISSUE TITLE
Request READ_EXTERNAL_STORAGE will fail on pre 4.1 devices

### ISSUE THREAD

**Issue by vanniktech** [tbruyelle/RxPermissions#20]
Since the `READ_EXTERNAL_STORAGE` was introduced with Android 4.1 the call to `ActivityCompat.requestPermissions` will return that the permission is denied on devices running Android 4.0 or below.

More information can be found here: https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html

In any case this library should return true when I call `.request(Manifest.permission.READ_EXTERNAL_STORAGE)` on devices below 4.1.

**Comment by tbruyelle** [comment]
Thanks for the report. 

I also read that post, and unlike `ActivityCompat`, `RxPermissions` doesn't delegate the permission request to `PackageManager` but returns true immediatly. So this issue is already handled.

**Comment by vanniktech** [comment]
Oh ok then sorry for opening the issue.

**Comment by tbruyelle** [comment]
No problem
