### ISSUE TITLE
VIVO x9 获取相机权限失败

### ISSUE THREAD

**Issue by puretsang** [tbruyelle/RxPermissions#200]
vivo x9 我把我相机权限关了，重新打开app,RxPermission.request() 返回给了我true,累崩...

**Comment by AnyLifeZLB** [comment]
Me too

**Comment by dlluotian** [comment]
同样。。。这样被vivo市场给打回来了

**Comment by 529523346** [comment]
同求

**Comment by gao746700783** [comment]
这是老外的  你们这样子写中文 人家会懵逼的好吗
vivo 小米 这些属于适配的，还得自己来搞下

**Comment by tbruyelle** [comment]
Please write the issue in english.
