### ISSUE TITLE
VIVO手机上用rxpermission没效果有人碰到过吗

### ISSUE THREAD

**Issue by 15707901235** [tbruyelle/RxPermissions#207]

**Comment by AnyLifeZLB** [comment]
Vivo X9 ,Android 7.1.1 ,  不管是怎样最后返回的结果都是你有权限了

**Comment by dlluotian** [comment]
楼主解决了没有

**Comment by zlq4863947** [comment]
目测是人品问题

**Comment by yys730** [comment]
是的，vivo很奇葩

**Comment by androidtyy** [comment]
我这VIVO手机 申请权限也不行,明明是没有权限的  却说有权限

**Comment by kamaelyoung** [comment]
oppo vivo.都这样

**Comment by iielse** [comment]
我这里崩溃了几次

**Comment by iielse** [comment]
魅族也是

**Comment by iielse** [comment]
# 195005432018-09-28 08:56:06 127OPPO PADM00Android 8.1.0,level 27 | # 195005 | 43 | 2018-09-28 08:56:06 127 | OPPO PADM00 | Android 8.1.0,level 27
-- | -- | -- | -- | -- | --
# 195005 | 43 | 2018-09-28 08:56:06 127 | OPPO PADM00 | Android 8.1.0,level 27
# 227004432018-09-28 04:46:14 862OPPO PADM00Android 8.1.0,level 27 | # 227004 | 43 | 2018-09-28 04:46:14 862 | OPPO PADM00 | Android 8.1.0,level 27
# 227004 | 43 | 2018-09-28 04:46:14 862 | OPPO PADM00 | Android 8.1.0,level 27
# 202006432018-09-28 04:46:04 195OPPO PADM00Android 8.1.0,level 27 | # 202006 | 43 | 2018-09-28 04:46:04 195 | OPPO PADM00 | Android 8.1.0,level 27
# 202006 | 43 | 2018-09-28 04:46:04 195 | OPPO PADM00 | Android 8.1.0,level 27
# 206004432018-09-27 13:34:35 412魅族 16TH PLUSAndroid 8.1.0,level 27 | # 206004 | 43 | 2018-09-27 13:34:35 412 | 魅族 16TH PLUS | Android 8.1.0,level 27
# 206004 | 43 | 2018-09-27 13:34:35 412 | 魅族 16TH PLUS | Android 8.1.0,level 27
# 225003432018-09-27 12:35:10 863魅族 M6 NOTEAndroid 7.1.2,level 25 | # 225003 | 43 | 2018-09-27 12:35:10 863 | 魅族 M6 NOTE | Android 7.1.2,level 25
# 225003 | 43 | 2018-09-27 12:35:10 863 | 魅族 M6 NOTE | Android 7.1.2,level 25
# 228002432018-09-27 12:29:23 064魅族 PRO 7 SAndroid 7.0,level 24 | # 228002 | 43 | 2018-09-27 12:29:23 064 | 魅族 PRO 7 S | Android 7.0,level 24
# 228002 | 43 | 2018-09-27 12:29:23 064 | 魅族 PRO 7 S | Android 7.0,level 24


这些用 rxpermission 挂了

**Comment by 317056658** [comment]
你们不知道用原生吗?

**Comment by dreamlivemeng** [comment]
在坚果pro上面也是这样，没有弹框，直接进回调方法了，但是并没有获取权限

**Comment by 490965536** [comment]
我的oppo也是不行.   当用户禁止了权限的时候,是无法收到回调的...

**Comment by tbruyelle** [comment]
Please write the issue in english.
