### ISSUE TITLE
Why not push to Maven central ?

### ISSUE THREAD

**Issue by saadfarooq** [tbruyelle/RxPermissions#21]
I was wondering what the reasoning is behind not putting this on Maven central or jcenter? I keep forgetting to add the special maven repository in my apps.

**Comment by tbruyelle** [comment]
Because I'm lazy. Maven central needs more than just an aar.

**Comment by saadfarooq** [comment]
Got it... will try to put up a PR when I get the time

**Comment by tbruyelle** [comment]
That would be nice
