### ISSUE TITLE
No possibility for an explanation popup or the like

### ISSUE THREAD

**Issue by martyglaubitz** [tbruyelle/RxPermissions#22]
As stated in [Requesting permissions](http://developer.android.com/training/permissions/requesting.html) one should check whether you need to explain the necessity to request certain permissions by using [ActivityCompat.shouldShowRequestPermissionRationale](http://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldShowRequestPermissionRationale(android.app.Activity, java.lang.String)) 

Right now the library offers no possibility to handle this case, should be easy to implement though...

**Comment by eleventigers** [comment]
@martyglaubitz https://github.com/tbruyelle/RxPermissions/blob/8116cfa74b4a71ae526ca44629b88eb3843e10de/lib/src/main/java/com/tbruyelle/rxpermissions/RxPermissions.java#L244

**Comment by tbruyelle** [comment]
Thanks @eleventigers 

@martyglaubitz if you're OK with the implementation, please close the issue.

**Comment by martyglaubitz** [comment]
oh there it is, very well...

**Comment by chond** [comment]
To solve the problem, this is the best thing
