### ISSUE TITLE
xamarin port

### ISSUE THREAD

**Issue by kibotu** [tbruyelle/RxPermissions#220]
just letting you know that i've added your project to nuget https://github.com/kibotu/Xamarin.RxPermissions

have a nice day

**Comment by epool** [comment]
Hi @kibotu , I'm not familiar at all with nuget, but the library is now at v0.10.1 what is the best way to sync up this repo with nuget and your repo? Could you do that? In advance thanks!

**Comment by kibotu** [comment]
will update soon, thanks for the info

**Comment by kibotu** [comment]
i've updated the nuget :) https://www.nuget.org/packages/RxPermissions/0.10.2

thanks for you  hard work, stay awesome!

**Comment by epool** [comment]
@kibotu cool! I'm closing this issue, I hope don't forget to mention here once we have a new release. Is there a way to automate this sync up?

**Comment by kibotu** [comment]
you could add  [![BuildVersion](https://buildstats.info/nuget/RxPermissions)](https://www.nuget.org/packages/RxPermissions/) if you want

**Comment by epool** [comment]
Thank you, I just added the badge to the readme file.
