### ISSUE TITLE
Rationalle Issue

### ISSUE THREAD

**Issue by rahulr4** [tbruyelle/RxPermissions#224]
This is not an issue but a general practice.
The purpose of "shouldShowRequestPermissionRationale" is basically we can show some sort of message that why do we require a permission ?
But in your library, if i deny the permission first time, go back and come back to that screen and ask permission again,
It should logically should send back the rationnalle callback but it ask the permisssion with never ask again and after denying it, then returns shouldShowRequestPermissionRationale true

Reference link :- https://en.proft.me/media/android/android_marshmallow_permissions.png

**Comment by epool** [comment]
@rahulr4 This is out of the scope of the library I guess and your use case depends on each app that uses this library, each app should implement its use case separately of this library.

Closing, please reopen if needed.

CC: @tbruyelle

**Comment by rahulr4** [comment]
The android patterns for permission states that the rationalle dialog should come before asking the permission. Your library does the opposite which is incorrect.
I denied the permission first time so next time rationalle callback should come first so that i can educate the user why i need the permission and then ask him. This is how it is done.
