### ISSUE TITLE
Best approach to show a previous tutorial or Dialog

### ISSUE THREAD

**Issue by XabierGoros** [tbruyelle/RxPermissions#227]
Google suggests to inform the user why you're gonna ask some permissions. One typical easy way is to show a dialog with some informative text, and when the user accepts the dialog proceed to ask those permissions.

In this reactive way, what would it be the best approach for that for this library? Since this wouldn't work within `onCreate` method:

    private val rxPermissions: RxPermissions by lazy { RxPermissions(this) }
    ...
    val mDialog = Dialog(this)
    mDialog.applyStyle(R.style.SimpleDialogLight)
        .title(getString(R.string.verify_activity_permission_needed_dialog_title))
        .positiveAction(getString(R.string.generic_ok))
        .positiveActionClickListener {
          mDialog.cancel()
          rxPermissions
              .request(Manifest.permission.READ_PHONE_STATE)
              .observeOn(AndroidSchedulers.mainThread())
              .subscribe { granted ->
                if (granted) {
                  doSomething()
                }
              }
        }
        .contentView(dialogMessageView)
        .cancelable(true)
        .show()

**Comment by epool** [comment]
@XabierGoros you code above should work as expected independently that it's no called in the `onCreate`. One reactive improvement could be making you dialog reactive too with something like this:
```kotlin
Completable.create(emitter -> {
mDialog.applyStyle(R.style.SimpleDialogLight)
    .title(getString(R.string.verify_activity_permission_needed_dialog_title))
    .positiveAction(getString(R.string.generic_ok))
    .positiveActionClickListener {
      mDialog.cancel()
      if (!emitter.isDisposed()) {
          emitter.onComplete()
      }
    }
    .contentView(dialogMessageView)
    .cancelable(true)
    .show()
})
.andThen(rxPermissions.request(Manifest.permission.READ_PHONE_STATE))
.filter{ granted -> granted }
.observeOn(AndroidSchedulers.mainThread())
.subscribe {
              doSomething()
          }
```
