### ISSUE TITLE
Library should call isPermissionRevokedByPolicy

### ISSUE THREAD

**Issue by vanniktech** [tbruyelle/RxPermissions#23]
Should not this library call the [`isPermissionRevokedByPolicy`](http://developer.android.com/reference/android/content/pm/PackageManager.html#isPermissionRevokedByPolicy%28java.lang.String,%20java.lang.String%29) method?

**Comment by tbruyelle** [comment]
I discover this method, it sounds very similar to `shouldShowRequestPermissionRationale()`.

I don't know if it should be implemented in the library, the only benefit in that case would be to handle the sdk version.

**Comment by vanniktech** [comment]
As far as I understood it there can be policies which do deny you to use that particular permission. The only thing that I do not know is whether `shouldShowRequestPermissionRationale` checks the `isPermissionRevokedByPolicy` internally or not.

**Comment by tbruyelle** [comment]
Fixed in 0.5.0
