### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by PrashamTrivedi** [tbruyelle/RxPermissions#25]
Before I fork and start working on changes, I would like to know your views on following.

1. On RxPermission's [initializer](https://github.com/tbruyelle/RxPermissions/blob/master/lib/src/main/java/com/tbruyelle/rxpermissions/RxPermissions.java#L43) you have used `getApplicationContext()` any reason of doing so?? IMO just a local context should be enough. 
2. Have you thought on passing Fragments and activities to play nicely with lifecycle? I am planning to extend it with Trello's RxLifeCycle library.
3. How about a Kotlin sibling of this library?
One more question
4. There are some bits of code that should be delegated to support lib rather than doing it manually, any reason not doing that?

**Comment by tbruyelle** [comment]
1. It prevents to leak an `Activity` if the user passes that kind of class in the method invocation.
2. What do you mean ?
3. Not planned, I'm not sure of what benefits can bring a Kotlin version of the library.
4. What are you talking about ? Please detail.

**Comment by PrashamTrivedi** [comment]
Point 2: trello's rxlifecycle library is developed to listen to activity or fragment and they will unsubscribe automatically once (certain event or) activity or fragment ends. I recommend you to check it out, and check if it can be integrated nicely.


Point 4: in the code there is a check for is marshmallow, and use it to get return permission granted or not. While support library does it. Why don't delegate this to support library rather than doing it manually?

**Comment by tbruyelle** [comment]
2. I know RxLifecycle, but I don't see the benefits of an integration with RxPermissions.

4. Support lib hides the result of version check, whereas I need the information to feed the `Observables`. The lib manipulates `Observables`, Support lib doesn't.

**Comment by PaulWoitaschek** [comment]
> 3. How about a Kotlin sibling of this library? One more question
Java is fully interoperable with kotlin. You can access every method in the library easily from Kotlin.
