### ISSUE TITLE
Android Jetpack

### ISSUE THREAD

**Issue by jemshit** [tbruyelle/RxPermissions#263]
Hi, i can not create `RxPermissions(fragment)` because Fragment is from `androidx.fragment.app` package. Is there any workaround ?

**Comment by jemshit** [comment]
I think it works even IDE shows error. Because i have 
```
android.useAndroidX=true
android.enableJetifier=true
```
in `gradle.properties`

**Comment by consp1racy** [comment]
Make sure to leave an issue report on issuetracker.google.com/issues if you have problems with the IDE.
