### ISSUE TITLE
不支持 AndroidX

### ISSUE THREAD

**Issue by yuhaoz** [tbruyelle/RxPermissions#267]
迁移至AndroidX后，Activity依赖的是AndroidX里面的AppCompatActivity，此时rxPermissions = new RxPermissions(MainActivity.this)会报错。

**Comment by ewoks** [comment]
Please write in english, that way you will increase chances that your ticket is noticed and not ignored and closed without resolution

**Comment by jp1017** [comment]
androidx here: https://github.com/jp1017/RxPermissions/releases/tag/androidx
