### ISSUE TITLE
API 26 runtime permission

### ISSUE THREAD

**Issue by dasbiswajit** [tbruyelle/RxPermissions#268]
My app needs below permissions. Which has been incorporated in AndroidManifest.xml

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-feature android:name="android.hardware.camera"/>
    <uses-feature android:name="android.hardware.autofocus"/>
After upgrading to API 26

> (targetSdkVersion 26)

 some functionality is not working. As I need to incorporate runtime permission. I am using [RxPermission][2] .
The problem is my most of the implementations placed on helper class(not inside main activity).
when I am trying to use helper library getting error - .[![Can not resolve constructor][1]][1]
I have tried with the following options too -

> RxPermissions rxPermissions = new RxPermissions((FragmentActivity) mContext);

As [RxPermission][2] require Fragment as target.Can we ask user all the permission in the main activity? A sample code will help me. Project code for [refarance][3] 

  [1]: https://i.stack.imgur.com/aBj0j.png
  [2]: https://github.com/tbruyelle/RxPermissions/
  [3]: https://github.com/kaku2015/WeatherAlarmClock/blob/master/WeAC/src/main/java/com/kaku/weac/db/LocalAlbumImagePickerHelper.java#L76

**Comment by ewoks** [comment]
IMHO this can be closed @tbruyelle

**Comment by dasbiswajit** [comment]
@ewoks. Thanks. I have solved it. Ofcourse don't want to make developer unmanageable. I am able to fix this calling Rxpermission from from main activity

**Comment by dasbiswajit** [comment]
Closing the request

**Comment by ewoks** [comment]
glad that it worked out
