### ISSUE TITLE
RxPermissions don't support AndroidX

### ISSUE THREAD

**Issue by lanzhu1993** [tbruyelle/RxPermissions#270]
When initializing objects ，
rxPermissions = new RxPermissions( (FragmentActivity)this);  
FragmentActivity.class is android.support.v4.app.FragmentActivity;
but AndroidX FragmentActivity.class is package androidx.fragment.app
Cause can not Cast

**Comment by lanzhu1993** [comment]
Thank you for your answer.

**Comment by jp1017** [comment]
androidx here: https://github.com/jp1017/RxPermissions/releases/tag/androidx

**Comment by aicaprio** [comment]
> This looks like a duplicate of #263.
> 
> > I think it works even IDE shows error. Because i have
> > ```
> > android.useAndroidX=true
> > android.enableJetifier=true
> > ```
> > in gradle.properties
> 
> Enable `jetifier` which will convert all dependencies that use the old support library (including RxPermissions) to using AndroidX instead.
> 
> https://developer.android.com/jetpack/androidx/migrate

But there is errors warning on compile time. How can u run success?

**Comment by consp1racy** [comment]
Does it work when you run build from command line?

**Comment by uziassantosferreira** [comment]
@jp1017 Hey, How I can use your version in my project? Did you publish this version?
