### ISSUE TITLE
没有适配vivo手机

### ISSUE THREAD

**Issue by androidtyy** [tbruyelle/RxPermissions#274]
VIVO手机不起作用

**Comment by sUnShinEo0** [comment]
vivo手机在拒绝权限后, 不再响应accept方法

**Comment by why168** [comment]
是的啊，你们怎么处理呢？

**Comment by lkang08** [comment]
在vivo x21上看是没问题的，请问下你们出现问题的机型是什么？

**Comment by ChuckHAI** [comment]
vivo x20 没有任何回调

**Comment by leifu1107** [comment]
vivo手机没适配

**Comment by HyFun** [comment]
vivo 手机 Android 8.0系统后采用google原生的权限验证方法，之前的用的是自己那套验证，RxPermission解决不了这个。我目前也没找到办法

**Comment by yanjiaxue** [comment]
锤子手机也不行

**Comment by tbruyelle** [comment]
Please write the issue in english.
