### ISSUE TITLE
提供android 9.0版

### ISSUE THREAD

**Issue by panhongjin** [tbruyelle/RxPermissions#278]
迁移到Android 9.0版，即Android support库迁移到AndroidX库上去的jar包。

**Comment by AndSync** [comment]
项目迁移AndroidX  就不能使用没有迁移到AdnroidX的三方库的了吗？

**Comment by panhongjin** [comment]
自己把代码下载，在重新导入AndroidX库就可以解决了

**Comment by tbruyelle** [comment]
Please write the issue in english.
