### ISSUE TITLE
Is it possible to provide an explanation view before permission is asked? 

### ISSUE THREAD

**Issue by Rainer-Lang** [tbruyelle/RxPermissions#28]

**Comment by tbruyelle** [comment]
Of course, but you have to do it yourself.

**Comment by Rainer-Lang** [comment]
But is there a way to integrate it seamless into the lib?

**Comment by tbruyelle** [comment]
No I don't want to add this kind of feature in the library. I don't want UI dependency.

**Comment by Rainer-Lang** [comment]
I understand you. 
But maybe you could give a tipp to do it with your lib.

**Comment by tbruyelle** [comment]
If I need to show an explanation before ask permissions, I would show a dialog with the explanation and trigger the permission request on dialog dismiss.
