### ISSUE TITLE
Warning: com.tbruyelle.rxpermissions.RxPermissions: can't find referenced method 'boolean hasCompleted()' in program class rx.subjects.Subject

### ISSUE THREAD

**Issue by atomd** [tbruyelle/RxPermissions#29]
rx.subjects.Subject removed the method `hasCompleted`.

**Comment by tbruyelle** [comment]
Already fixed in #24, but I need to release it. I will do it asap,

**Comment by tbruyelle** [comment]
0.5.1 released, it should fix your problem.
