### ISSUE TITLE
Update sample with non-lambdas

### ISSUE THREAD

**Issue by theblixguy** [tbruyelle/RxPermissions#30]
The sample app and the sample code in description uses Lambda, which many people aren't aware of (the syntax) nor is supported by Android so please add a sample without Lambdas so we can understand  how to use it without Lambdas

**Comment by tbruyelle** [comment]
If you use Android Studio, type `new Ctrl+Space` and it will suggest the correct class to implement.

**Comment by AeonDave** [comment]
there are too many problems right now for lambda expression in android studio.
ctrl+space shows many class but do not suggest the correct one to implement.
plesae add just an easy sample so we can understand. Thank you

**Comment by tbruyelle** [comment]
Ok I removed retro lambda usage from the sample app.

**Comment by PaulWoitaschek** [comment]
Lambdas are pretty much the standard.

Especially now as Jack is coming out every developer who doesn't understand lambdas should just learn them. Its just a language feature. RxJava is unreadable without them.
