### ISSUE TITLE
配合使用AutoDispose失败

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [tbruyelle/RxPermissions#305]
如果配合AutoDispose使用的话，as(AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(lifecycleOwner))
之后subscribe()中的判断就不会执行

反之，则正常

**Comment by DancingSnowInFingertips** [comment]
If used with autodispose, 
as (AutoDispose.autoDispose (AndroidLifecycleScopeProvider. from (lifecycleOwner))

After that, the judgment in subscribe () will not be executed

**Comment by SuperXpher** [comment]
Me too.

**Comment by relish-wang** [comment]
use this please:
```java
.as(AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(this, Lifecycle.Event.ON_DESTROY)))
```
