### ISSUE TITLE
jcenter sync request

### ISSUE THREAD

**Issue by Piasy** [tbruyelle/RxPermissions#31]
Please sync this library into jcenter.

**Comment by jasondelport** [comment]
+1 

I use Ben Manes gradle versions plugin to check what is the latest version of my dependencies and the only dependency I have found that it can't detect is this one. 

https://github.com/ben-manes/gradle-versions-plugin

Great project by the way, much appreciated. :)

**Comment by tbruyelle** [comment]
Done
