### ISSUE TITLE
锤子Pro2 拒绝权限后，一直返回true

### ISSUE THREAD

**Issue by suoyj** [tbruyelle/RxPermissions#316]

**Comment by liangsaifei** [comment]
不止锤子吧，你试试 oppo ，vivo会有惊喜。

**Comment by galuszkak** [comment]
Hi @tbruyelle,

I think this is duplicate and  can be closed in favor of #301 .

**Comment by tbruyelle** [comment]
@galuszkak oh can you read chinese ?

That's actually bring a topic I would like to discuss, what should we do with non-english issue ?
I was tempted to just close them with a comment asking for english, wdyt ?

**Comment by galuszkak** [comment]
@tbruyelle well, I'm not that good. I tried to put this into Google Translate and by looking on translation I was assuming that it's same problem. 

Around non english comments, if we don't have maintainer that knows language in which issue is filled I think safe assumption is to close with kind ask to reopen it if it will be in english.

**Comment by TakmingMark** [comment]
Yes, It's same thing right.

**Comment by tbruyelle** [comment]
Closed because duplicate with #301
