### ISSUE TITLE
RxPermissions support for RxJava3

### ISSUE THREAD

**Issue by nguyenhoc89** [tbruyelle/RxPermissions#317]
Do you have any plan to update RxPermissions for RxJava3?

**Comment by zhupengxiang** [comment]
I also want to know

**Comment by ndangnguyen** [comment]
You can use these files
https://gist.github.com/ndangnguyen/60618ceb367d3b9a25814f3b9303f225

**Comment by zhupengxiang** [comment]
@ndangnguyen   How does your file and class name not match, missing a RxPermissionsFragment

**Comment by ndangnguyen** [comment]
@zhupengxiang updated

**Comment by hoanghiephui** [comment]
Okey

**Comment by Steppschuh** [comment]
[Here's](https://github.com/niklasvd96/RxPermissions) a fork that migrated to RxJava3.

**Comment by hoanghiephui** [comment]
Ok

**Comment by itsnicerdx** [comment]
I hope  author can update RxPermissions for RxJava3

**Comment by itsnicerdx** [comment]
I hope author can update RxPermissions for RxJava3，thanks

**Comment by galuszkak** [comment]
Hi @nguyenhoc89 , 

I've created PR for this in #326

**Comment by tbruyelle** [comment]
done with #326
