### ISSUE TITLE
Re-requesting permission fails

### ISSUE THREAD

**Issue by patloew** [tbruyelle/RxPermissions#32]
In my app, I’m trying to re-request the permission every time it fails via a non-cancelable AlertDialog, where the only action requests the permission again. However, when re-requesting the permission, `onCompleted()` happens, without `onNext()`:

	// First request:
	D/MainFragment: [@Observable :: @InClass -> MainFragment :: @Method -> getPermissionsObservable()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onSubscribe()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onNext() -> false]
	D/MainFragment: [@Observable#getPermissionsObservable -> @SubscribeOn -> main :: @ObserveOn -> main]
	D/MainFragment: [@Observable#getPermissionsObservable -> onUnsubscribe()]
	// Second (retry) request:
	D/MainFragment: [@Observable :: @InClass -> MainFragment :: @Method -> getPermissionsObservable()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onSubscribe()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onCompleted()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onTerminate()]
	D/MainFragment: [@Observable#getPermissionsObservable -> @Emitted -> 0 elements :: @Time -> 99 ms]
	D/MainFragment: [@Observable#getPermissionsObservable ->  :: @ObserveOn -> main]
	D/MainFragment: [@Observable#getPermissionsObservable -> onUnsubscribe()]

The first request in the fragment happens in `onActivityCreated()`. After debugging, I saw the problem was that `onDestroy()` of the `ShadowActivity` from the first try is called before `onRequestPermissionsResult()` of the second Activity, therefore [calling `onCompleted()` on all subjects](https://github.com/tbruyelle/RxPermissions/blob/master/lib/src/main/java/com/tbruyelle/rxpermissions/RxPermissions.java#L304). 

	D/RxPermissions: Requesting permissions android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: startShadowActivity android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: onRequestPermissionsResult  android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: Requesting permissions android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: startShadowActivity android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: onDestroy
	D/RxPermissions: onRequestPermissionsResult  android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: onDestroy

However, this **should** not happen, since the Activity is started with `FLAG_ACTIVITY_NEW_TASK`, which indicates that only one Activity instance can exist at a time. The correct framework behavior would be to call `onNewIntent()` in this case. In my case, a new `ShadowActivity` instance is created and its `onCreate()` is called before `onDestroy()` of the old `ShadowActivity`. This seems to be some sort of Android framework bug. I tried adapting the sample app with a similar use of RxPermissions, but there I couldn’t reproduce this behaviour.

Removing the `onDestroy()` callback in `RxPermissions` class solves the issue, but I’m not sure if this could lead to problems with configuration changes (see pull request #14, where this was added). However, in normal cases, removing `onDestroy()` should not be a problem, because subjects are removed in the `onRequestPermissionsResult()` callback anyway.

**Comment by tbruyelle** [comment]
Well, I also use the library to request multiple times a critical permission, but I don't have the problem you describe. That said I'm not using those damned fragments.

Rather than removing the `onDestroy` content, could you try to wipe the subject list at the end of `RxPermissions.onDestroy()` :

```diff
 void onDestroy() {
        log("onDestroy");
        // Invoke onCompleted on all registered subjects.
        // This should un-subscribe the observers.
        for (Subject subject : mSubjects.values()) {
            subject.onCompleted();
        }
+      mSubjects.clear();
    }
```

Tell me if it fixes your issue.

**Comment by patloew** [comment]
I tried your fix, but it didn’t work.

	D/MainFragment: [@Observable :: @InClass -> MainFragment :: @Method -> getPermissionsObservable()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onSubscribe()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onNext() -> false]
	D/MainFragment: [@Observable#getPermissionsObservable -> @SubscribeOn -> main :: @ObserveOn -> main]
	D/MainFragment: [@Observable#getPermissionsObservable -> onUnsubscribe()]
	D/MainFragment: [@Observable :: @InClass -> MainFragment :: @Method -> getPermissionsObservable()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onSubscribe()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onCompleted()]
	D/MainFragment: [@Observable#getPermissionsObservable -> onTerminate()]
	D/MainFragment: [@Observable#getPermissionsObservable -> @Emitted -> 0 elements :: @Time -> 223 ms]
	D/MainFragment: [@Observable#getPermissionsObservable ->  :: @ObserveOn -> main]
	D/MainFragment: [@Observable#getPermissionsObservable -> onUnsubscribe()]

The problem with this is that still `onDestroy()` gets called before `onRequestPermissionResult()`:

	D/RxPermissions: Requesting permissions android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: startShadowActivity android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: onRequestPermissionsResult  android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: Requesting permissions android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: startShadowActivity android.permission.ACCESS_FINE_LOCATION
	D/RxPermissions: onDestroy
	D/RxPermissions: onRequestPermissionsResult  android.permission.ACCESS_FINE_LOCATION

In this case, the subject is not available anymore in `onRequestPermissionResult()`, therefore throwing an exception:

	java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

**Comment by tbruyelle** [comment]
Oh I think I get it this time. So as you explained there's no reason why an activity started with `FLAG_ACTIVITY_NEW_TASK` propagate a `onDestroy` event to a singleton like the `RxPermissions` class.

I think we can safely remove the `ShadowActivity.onDestroy` method.

Could you check if it's OK for you and then open a PR ? I will try to release it quickly.

**Comment by patloew** [comment]
Was solved by #33.

**Comment by tbruyelle** [comment]
Sorry I'm going to reverse that change because it breaks configuration change handling.

When you request a permission, you see the permission dialog, if before answer you rotate your phone, your app is restarted and the permission dialog pops again automatically (it's not because of RxPermissions). If you answer at this time, the rx chaining should be invoked properly, but not any more since that change.

**Comment by patloew** [comment]
In `onDestroy()` you call `onCompleted()` on all subjects for unsubscribing. However, in my opinion, users should unsubscribe their Subscriptions anyway, when their Activity gets destroyed (e.g. with a `CompositeSubscription`).

Wouldn’t it be better to have a separate list, which contains all subjects that did not receive a result from permission requests? I created pull request #37 for implementing this. This way, configuration changes are handled correctly, while also fixing this issue.

**Comment by hellohelloye** [comment]
is the permission dialog automatically created when you 

`rxPermissions.request(Manifest.permission.RECORD_AUDIO).subscribe(new Action1<Boolean>() {
            @Override
            public void call(Boolean aBoolean) {
                Log.d(getClass().getSimpleName(), "inside call");

            }
        });`

or you need to create the view by yourself?

**Comment by GreenDeveloperMukesh** [comment]
I get This issues while using this code in 4.4 Kitkat
 RxPermissions rxPermissions = new RxPermissions(SplashActivity.this);         rxPermissions.setLogging(true);

E: FATAL EXCEPTION: main
   Process: com.package.test, PID: 8860
   java.lang.VerifyError

Are there any solutions for this ????
