### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Noshilyahgg** [tbruyelle/RxPermissions#322]
### Prerequisites

* [] Put an X between the brackets on this line if you have done all of the following:
    * Read carefully README: https://github.com/tbruyelle/RxPermissions#rxpermissions
    * Checked that your issue isn't already filed: https://github.com/tbruyelle/RxPermissions/issues

### Issue description
[A clear and concise description of what the bug is.]

### Actual behavior
[A clear and concise description of what actually happened.]

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Steps To Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

### RxPermission usage code **(extremely Required)**
Give a comprehensive example of how exactly RxPermission is used (Use [gists](https://gist.github.com/) or style code with styling markdown). 
Provide all info from the beginning that includes:
- How and where RxPermission was instantiated. 
- In what lifecycle method. Activity or fragment. Give info about screen view hierarchy if it really complicated and has many nested Fragments.
- Some additional info or important context if needed. 

### Lib Version
Give info about what lib version do you use

**Screenshots**
Add screenshots to help explain your problem only If it will be handy for your use case.
If issued only with particular device provide device info 
 - Device: [e.g. Nexus 5]
 - OS version: [Android 5.1]

**Comment by galuszkak** [comment]
@tbruyelle I think this bug can be safely closed.

**Comment by tbruyelle** [comment]
indeed :)
