### ISSUE TITLE
你好，请问有升级到Rxjava3的计划呢？

### ISSUE THREAD

**Issue by TomorrowDreamer** [tbruyelle/RxPermissions#327]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

现在很多三方库都支持Rxjava3了,确认下本库是否有支持Rxjava3的计划？谢谢回复~

**Comment by galuszkak** [comment]
@TomorrowDreamer RxJava 3 is supported from version 0.12 .

@tbruyelle I think this can be closed.
