### ISSUE TITLE
Move library to maven central

### ISSUE THREAD

**Issue by thesurix** [tbruyelle/RxPermissions#341]
This request is related to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please move this library to maven central, there is great HOWTO article --> https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

**Comment by epool** [comment]
@thesurix the library is no longer using jcenter since a while ago, it's using [Jitpack](https://github.com/tbruyelle/RxPermissions#setup)

**Comment by thesurix** [comment]
You are right, thanks!
