### ISSUE TITLE
NoSuchMethodError on Android 4.3.1

### ISSUE THREAD

**Issue by ReginFell** [tbruyelle/RxPermissions#35]
Hi everyone. 
Have 
`java.lang.NoSuchMethodError:Lcom/tbruyelle/rxpermissions/ShadowActivity;.requestPermissions`
 on **Batmobile XT320.** Any idea how to prevent this kind of error? 

![default](https://cloud.githubusercontent.com/assets/3144106/13391875/9789f624-dedf-11e5-801f-93a333b24d19.jpg)

**Comment by tbruyelle** [comment]
Well that's weird, you get that error because the code is executed on a pre-6 version of Android. This isn't supposed to happen, in `RxPermissions` the version is checked before invoking that method.

You're not trying to start the `ShadowActivity` manually don't you ?

**Comment by ReginFell** [comment]
Nope, i used it in this way https://gist.github.com/ReginFell/49538a7edfed90a6639a

Parrent activity is AppCompatActivity.

**Comment by tbruyelle** [comment]
That shouldn't happen, do you see this error frequently in your crashlytics?

**Comment by tbruyelle** [comment]
Closed for no response frome submitter

**Comment by shayanzoro** [comment]
I have the same problem

Fatal Exception: java.lang.NoSuchMethodError
com.tbruyelle.rxpermissions.ShadowActivity.requestPermissions
com.tbruyelle.rxpermissions.ShadowActivity.handleIntent (ShadowActivity.java:27)
com.tbruyelle.rxpermissions.ShadowActivity.onCreate (ShadowActivity.java:16)

**Comment by tbruyelle** [comment]
Use last version please.
