### ISSUE TITLE
Cannot access class 'io.reactivex.rxjava3.core.Observable'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by leif123** [tbruyelle/RxPermissions#354]
### Issue description
val request = rxPermissions.request(Manifest.permission.CAMERA)

Cannot access class 'io.reactivex.rxjava3.core.Observable'. Check your module classpath for missing or conflicting dependencies
![1](https://user-images.githubusercontent.com/22392309/160242936-a4822735-fb89-440e-af3b-ac46bada3f30.png)
![2](https://user-images.githubusercontent.com/22392309/160242940-54665354-6058-4583-8c33-5512f52e9d26.png)
![3](https://user-images.githubusercontent.com/22392309/160242952-d3b34d78-379b-4f2a-a7dd-258b9f10dee5.png)

**Comment by leif123** [comment]
add
implementation 'io.reactivex.rxjava3:rxjava:3.0.4'

**Comment by pravingaikwad07** [comment]
add this lib in app module:

` implementation 'io.reactivex.rxjava3:rxjava:3.1.4'
`
