### ISSUE TITLE
ShadowActivity background

### ISSUE THREAD

**Issue by PingForward** [tbruyelle/RxPermissions#39]
Please change the ShadowActivity background to transparent if it is possible.

**Comment by tbruyelle** [comment]
Do you see it ? The theme used for this activity is already transparent

**Comment by PingForward** [comment]
It shows gray background and appear animation for activity when dialog triggered.
Nexus 5 and emulator tested. 
![screenshot_20160316-134959](https://cloud.githubusercontent.com/assets/17492722/13809923/37b53f1e-eb7e-11e5-89f9-e5723ff6d166.png)
![screenshot_20160316-024737](https://cloud.githubusercontent.com/assets/17492722/13809935/44450a34-eb7e-11e5-9015-4aa4083f9ea6.png)

**Comment by tbruyelle** [comment]
I never noticed that problem, and I tested also on N5.

Are you sure it's not something due to the moment you request the permission ? I would like to have some details of your usage.

**Comment by PingForward** [comment]
Here is my code implementation. It is v4.support fragment inside AppCompatActivity with Theme.AppCompat.Light.DarkActionBar theme

```
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (savedInstanceState == null) {
            requestGpsPermission();
        }
    }

    private void requestGpsPermission() {
        RxPermissions.getInstance(getActivity())
                .request(Manifest.permission.ACCESS_FINE_LOCATION)
                .subscribe(granted -> {
                    if (granted) { // Always true pre-M
                      // start service
                    } else {
                        requestGpsPermission();
                    }
                });
    }
```
Also I tried to start it with timer to ensure that UI created but the same result gray backgroud.
I think the issue in the used theme. You set for shadow activity not app compat theme and on M devides it is not working.

**Comment by tbruyelle** [comment]
Well not sure if it's related to your ptoblem but you shouldn't condition the permission request with `savedInstanceState == null`. In case of configuration change, the lib won't work properly.

Do you use the last version 0.6.1 ?

**Comment by tbruyelle** [comment]
Closed for no response from the submitter

**Comment by PingForward** [comment]
I will try it in a few days...
Migration to 0.6.x
..... and ensureEach(permission...). Read the** second example** to see how to use them.

Where is examples with ensure??

**Comment by PingForward** [comment]
@tbruyelle no result on v0.7.0. Gray background on the shadow activity

**Comment by tbruyelle** [comment]
Did you move the call ouside the `if (savedInstanceState == null)` ?

**Comment by PingForward** [comment]
@tbruyelle yes I did

**Comment by PingForward** [comment]
Sorry man it seems my fault. I set theme to the shadow activity manually and it start working. I did that before but no luck. Now it is working. Thanks!
```
 <activity
            android:name="com.tbruyelle.rxpermissions.ShadowActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
```

**Comment by tbruyelle** [comment]
This is already the case, I don't understand why you need to override it. Moreover Fullscreen is not necessary.

https://github.com/tbruyelle/RxPermissions/blob/master/lib/src/main/AndroidManifest.xml#L11

Anyway it works for you, fine.
