### ISSUE TITLE
Result is lost with Do not keep activities ON

### ISSUE THREAD

**Issue by artesa** [tbruyelle/RxPermissions#40]
Hello,

The result of permission request is lost in the following case (can be easily reproduced with your sample):
1. Go to Settings and enable "Do not keep activities" mode.
2. Open the sample.
3. Press "Enable camera"
4. Press Home button.
5. Retrieve the app from the recent apps.
6. Press "Allow".
Actual result: Noting happens.
Expected result: Camera is opened.

While staying a rare case, it's a bit annoying, especially when using the library in production. I would be interested to know if you have any idea how to avoid this issue (except that to reject requesting permission by a trigger in a whole).

Thank you in advance.

**Comment by tbruyelle** [comment]
Interesting, I missed that test. I'll look into it.

**Comment by tbruyelle** [comment]
With "do not keep activities" enabled, it works with a standard config change (screen rotate for instance) but not with the steps you described.
So a config change doesn't kill your activity like the home button followed by back from recent app, that's frustrating. The proof is `ShadowActivity.onDestroy` isn't invoked from the framework in that second case. Without that call, `RxPermissions` isn't able to remind previous permission requests, causing the issue you created.

Do you know why in that case the android lifecycle is ignored ?

**Comment by grimmy0** [comment]
According to documentation of onDestroy() method - "Note: do not count on this method being called as a place for saving data!" (http://developer.android.com/reference/android/app/Activity.html#onDestroy()). Also there is no guaranty that system actually will call onDestroy(). So may be you should move that code to any other place?

**Comment by tbruyelle** [comment]
Ok I'll move it to `onStop()` probably.

**Comment by tbruyelle** [comment]
Released in version 0.6.1, thanks for the report.

**Comment by artesa** [comment]
Checked - now works as expected.
Thank you!
