### ISSUE TITLE
Return a detailed permission report rather than just a boolean

### ISSUE THREAD

**Issue by vanniktech** [tbruyelle/RxPermissions#5]
Would not it be better if the Subscriber would get a `Map<String, Boolean>` and from there we could see which permission was / is denied and which was / is accepted.

**Comment by tbruyelle** [comment]
It depends on the usage. Most of the time I think people only want to know if the user has granted all the requested permissions. So a simple boolean is enough.

That said, your proposal is good. What if we add another method to the API, let's say `requestDetailed()` which returns an `Observable<Map<String,Boolean>>`  ?

**Comment by vanniktech** [comment]
Yup that'd work. Though I think it should return the concrete type of the map. So if the library would internally use HashMap it should also return HashMap type. That way the consumer of the library knows what he's working with.

**Comment by tbruyelle** [comment]
I'm not sure about the map thing. Are you saying the method should return `Observable<HashMap<String, Boolean>>` rather than `Observable<Map<String, Boolean>>` ?

**Comment by vanniktech** [comment]
Exactly. That way the consumer knows he gets HashMap hence he knows the implementation details. Methods should always accept the most abstract input (Collection, Map, ...) but return the most concrete return type (ArrayList, HashSet, HashMap, TreeMap).

**Comment by alorma** [comment]
Not agree with `HashMap` return.

It's better to work with interfaces rather than implementations, if in a future it changes to LinkedMap, clients should changes the implementation

**Comment by tbruyelle** [comment]
Yep agree with @alorma. 
Until now I never heard of that kind of rule. And in this library's context, I don't see any benefit for the consumer to explicitly know the concrete type of the `Map`.

**Comment by dadino** [comment]
I'm still at the start with RxJava so this may sound silly.
Wouldn't it be correct to have a .subscribe event for every permission?

    RxPermissions.getInstance(context) 
                .request(Manifest.permission.CAMERA,
                       Manifest.permission.READ_PHONE_STATE)
                .subscribe(permission -> {
                    if (permission.isGranted()) {
                       // Permission granted
                    } else if (permission.shouldRequestAgain()){
                       // Permission was denied, but you could request it again
                    } else {
                       // Permission was denied and the user doesn't want to be bothered
                    }
                });

    class Permission{
      String permission;
      int state; //granted, denied, denied_could_request_again
    }

You could also call onCompleted and pass a List<Permission> if you want them together.

**Comment by tbruyelle** [comment]
Not silly at all, but interesting. This is absolutely feasible with RxJava.

If I'm right,  `permission.shouldRequestAgain()` is related to `shouldShowRequestPermissionRationale`. I started a basic support for this method in #8, but implemented it differently. I chose to create a independent method so you can mix the observables, like [here](https://github.com/tbruyelle/RxPermissions/pull/9/files#diff-dd59e011627697b372d3b0429739ae71R35).

what is the way you prefer ?

**Comment by dadino** [comment]
Yes they are related, just wrong spelling on my part.
My way should be less code to write and maybe a little more readable, but, again, I've been using RxJava for 3 days, I don't understand best practices.

**Comment by tbruyelle** [comment]
Yes there is less code in theory but what do you do mostly if `shouldShowRequestPermissionRationale` returns `true` ? 
You show the user an explanation with a dialog and once he agrees, request the permission a second time. That's why I did it like that. 

That said, I'm not 100% sure this is the best way.

**Comment by tbruyelle** [comment]
I just create that PR, please tell me if this fits your needs. 
Please comment on the PR.

**Comment by tbruyelle** [comment]
Released in version 0.3.0
