### ISSUE TITLE
Trigger view is not existing in any initialisation event

### ISSUE THREAD

**Issue by MFlisar** [tbruyelle/RxPermissions#50]
I have a view based activity and depending on the current state, I change my menu in the toolbar while activity is shown. This means, I can not create a view click observable in an init event, because the view may not be existing...

Any idea how to solve that problem?

**Comment by tbruyelle** [comment]
When the permission request is triggered by an action menu, you're right it's not trivial to implement it during an initialization phase.

Although it's not ideal, I suggest to use a *subject* to register the permission request during the initialization phase of the activity, and then emit an arbitrary item in that *subject* in the menu click listener when you want to trigger the permission request.

I can provide an example if necessary. Or if you find a better way to do that let me know.

**Comment by MFlisar** [comment]
I had the same idea and am using it that way currently... just thought you have a better idea as this somehow makes the usage a little unintuitive...

So no need for an example, thanks for your thoughts on this

**Comment by tbruyelle** [comment]
Fine, that's also how I use it. 
I would like to provide a better way but it would require dependencies to menu listeners and things like that and so finally I prefer no.

**Comment by MFlisar** [comment]
One general question:

Is it necessary to REUSE the subject? Or can I create a new subject whenever the activity is created? In the end it comes to following question: Should I use a static subject or not?

**Comment by tbruyelle** [comment]
Good question, I don't know. On my side I didn't reuse the subject. Not sure if it's good or bad...
