### ISSUE TITLE
Should I call unsubscribe() when my Activity is destoryed?

### ISSUE THREAD

**Issue by kirsting** [tbruyelle/RxPermissions#52]
I didn't see unsubscribe() be called in the sample. Will the permission Subjects leak the memory of Activity if I don't unsubscribe it?

**Comment by tbruyelle** [comment]
I use the library inside a project monitored with leakcanary and no leak
were detected.

**Comment by micHar** [comment]
If the lib calls onCompleted on the subscriber, then it is perfectly safe not to unsubscribe. After onCompleted the subscriber will be garbage collected.
And I assume it calls onCompleted, because there is no reason not to (but have not checked it in the code).

**Comment by tbruyelle** [comment]
Yep https://github.com/tbruyelle/RxPermissions/blob/4c4d4e1e84ad1fcf390342c493c8ed09b5e613ca/lib/src/main/java/com/tbruyelle/rxpermissions/RxPermissions.java#L291

**Comment by o-antsiferov** [comment]
I'm also using LeakCanary to detect possible leaks and it detects them after changing orientation back and forth for some times: 
![device-150152](https://user-images.githubusercontent.com/1282126/28267051-eb953392-6b00-11e7-8c92-3f232f1753fa.png)
