### ISSUE TITLE
When asked `Manifest.permission.READ_CONTACTS` always return true

### ISSUE THREAD

**Issue by lovejjfg** [tbruyelle/RxPermissions#56]
When i use `RxPermissions` in my devices(HTC desire 816  Android 6.0):     

    RxView.clicks(bt1)
                .compose(RxPermissions.getInstance(getApplicationContext())
                        .ensure(Manifest.permission.READ_CONTACTS))
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean aBoolean) {
                        if (aBoolean) {
                            List<ContactBean> contacts = ContactUtils.getContacts(getApplicationContext());
                            Log.i(TAG, "call: " + contacts);
                        } else {
                            Toast.makeText(getApplicationContext(), "REFUSED！", Toast.LENGTH_SHORT).show();
                        }
                        Log.i(TAG, "callxx: " + aBoolean);

                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        Log.e(TAG, "callxxx: ", throwable);
                    }
                });

I'm   confused that these codes always return true even if i chose `Deny` in the dialog !
What‘s wrong with these codes ?

**Comment by lovejjfg** [comment]
compile 'com.tbruyelle.rxpermissions:rxpermissions:0.7.0@aar'
    compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'

**Comment by tbruyelle** [comment]
That's weird, how did you declare the permission in the manifest file ?

**Comment by tbruyelle** [comment]
Closed because no response
