### ISSUE TITLE
add android.permission.CAMERA 权限同时检测时一直失败

### ISSUE THREAD

**Issue by luxiaoming** [tbruyelle/RxPermissions#57]
RxView.clicks(findViewById(R.id.photo))
                .compose(RxPermissions.getInstance(this).ensure(Manifest.permission.READ_EXTERNAL_STORAGE))
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean granted) {
                        if (granted) {
                            PhotoPickerIntent intent = new PhotoPickerIntent(DiaryPost.this);
                            intent.setPhotoCount(1);
                            intent.setShowCamera(true);
                            intent.setShowGif(false);
                            startActivityForResult(intent, REQUEST_CODE);
                        } else {
                            showToast(R.string.no_permission);
                        }
                    }
                });

**Comment by tbruyelle** [comment]
?
