### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by awhgwqpeogh** [tbruyelle/RxPermissions#59]
![log](https://cloud.githubusercontent.com/assets/14243201/16717351/424f6e16-4747-11e6-860b-a15fbd437097.png)

**Comment by jvbreen1** [comment]
@huahongyang What is your targetSdkVersion and compileSdkVersion in your build.gradle?

**Comment by huahongyang** [comment]
@jvbreen1 targetSdkVersion 23 ,compileSdkVersion 23 and the crash api level is 19

**Comment by jvbreen1** [comment]
What are you trying to do when the crash happens? Do you have any other
libraries in your app? Can you reproduce on a sample app?

**Comment by huahongyang** [comment]
i don't have the crash device,i test my app in cloud testing,so i  can't debug it to analyze the problem,i only have  is the crash monitoring log

**Comment by huahongyang** [comment]
@jvbreen1 i don't have the crash device,i test my app in cloud testing,so i can't debug it to analyze the problem,i only have is the crash monitoring log

**Comment by dkhmelenko** [comment]
@huahongyang API level should be min 23 (Android 6 Marshmallow). And you are using API level 19, where `requestPermissions` method doesn't exist.
Whenever you use in code this library, the calls will be highlighted by Android Studio that the methods are available only in API level 23.

**Comment by boyw165** [comment]
Could use the following sample to maximize the compatibility.

```
// Here, thisActivity is the current activity
if (ContextCompat.checkSelfPermission(thisActivity,
                Manifest.permission.READ_CONTACTS)
        != PackageManager.PERMISSION_GRANTED) {

    // Should we show an explanation?
    if (ActivityCompat.shouldShowRequestPermissionRationale(thisActivity,
            Manifest.permission.READ_CONTACTS)) {

        // Show an expanation to the user *asynchronously* -- don't block
        // this thread waiting for the user's response! After the user
        // sees the explanation, try again to request the permission.

    } else {

        // No explanation needed, we can request the permission.

        ActivityCompat.requestPermissions(thisActivity,
                new String[]{Manifest.permission.READ_CONTACTS},
                MY_PERMISSIONS_REQUEST_READ_CONTACTS);

        // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
        // app-defined int constant. The callback method gets the
        // result of the request.
    }
}
```

**Comment by tarasantoshchuk** [comment]
@huahongyang 
are you starting ShadowActivity directly in your code?
Because normally RxPermissions wouldn't start it on devices with API < 23.

**Comment by tarasantoshchuk** [comment]
@awhgwqpeogh any updates?

**Comment by tarasantoshchuk** [comment]
@tbruyelle 
there are 2 instances of this crash in my app, but both are on emulators with Android version 4.1.1

However, since ShadowActivity is public class (and not package-protected) some of library users might start ShadowActivity directly in their code - which will cause NoSuchMethodException on API <23.

Maybe we should make ShadowActivity package-protected?

**Comment by tbruyelle** [comment]
> since ShadowActivity is public class (and not package-protected) some of library users might start ShadowActivity directly in their code

That's crazy

> Maybe we should make ShadowActivity package-protected?

why not

**Comment by PaulWoitaschek** [comment]
I'm seeing that crash in [my audibook player](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer) too.

Its a 4.3.1	 Batmobile generic XT320 device.
I'm pretty sure [none of my used libraries](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/build.gradle#L48) are starting the activity.

**Comment by tarasantoshchuk** [comment]
@PaulWoitaschek 
can you check whether the device is rooted or not?

**Comment by PaulWoitaschek** [comment]
Nope, but the same device has a extremely weird behavior at some other place. I think if there are no furhter reports its safe to ignore this issue.

At another place one of my activities gets started with a missing key in its intent. (I only create an intent through a static factory and never overwrite it so that can't be possible)
