### ISSUE TITLE
The permission dialog will not show again

### ISSUE THREAD

**Issue by mengdd** [tbruyelle/RxPermissions#61]
**Reproduce steps:**
The situation is like this:
When requesting one permission, the dialog shows. 
Then do not choose ALLOW nor DENY, keep the dialog showing and background the app.
Open a deep link to restart the app. the permission dialog gone.
Then request the same permission in the first step, the permission dialog will not show, nothing happens at all.

**Bug reason:**
Because `ShadowActivity` in `RxPermissions` is in another task, when opening deep link, we open activity in original task. So the dialog is gone.
When we request same permission next time, the `mSubjects` still holds the permission so `RxPermissions` does not start shadow activity again.
Actually the `ShadowActivity` is still alive but we can not see it.

**Comment by mengdd** [comment]
Sorry I was wrong about the analysis, the task part.
After some reading about the launch mode and the new task flags, I think the ShadowActivity is still in the same task.
I'm still doing some experiments to find out a good way to fix the problem.

**Comment by dreamcontinue** [comment]
Is there a good way to resolved? I just got the same problem as well.

**Comment by simformsolutions** [comment]
i am facing same issue.. can you please provide solution ?

**Comment by epool** [comment]
probably version `0.9.0` solve the problem, but now sure. let us know if that version solves the problem.

**Comment by mengdd** [comment]
Just tried the version 0.9.4, the issue still exists.

**Comment by epool** [comment]
@mengdd could you please provide us a basic project with the deep link configuration you are trying, to reproduce this issue?

**Comment by mengdd** [comment]
@epool Hi, I just create a sample project here: https://github.com/mengdd/RxPermissionsSample

Maybe it's because it involves two activities here. 
When there is one activity, the deep link works well. 

But in my sample project, it shows the bug.

**Comment by hijamoya** [comment]
Still encounter the issue in current master.
