### ISSUE TITLE
Testing problem granted always true

### ISSUE THREAD

**Issue by PopTudor** [tbruyelle/RxPermissions#64]
Hello,
I am trying to test each branch of granted/not granted permissions but with I don't know should approach this because I always get granted == true.
```java
public void onCreate(Bundle savedInstanceState) {
RxPermissions.getInstance(getActivity())
				.request(Manifest.permission.READ_EXTERNAL_STORAGE)
				.subscribe(new Action1<Boolean>() {
					@Override
					public void call(Boolean granted) {
						if (granted) {
							injectComponent();
						} else {
							// Oups permission denied
							getActivity().onBackPressed();
						}
					}
				});
}
```
Test
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,sdk = 23)
public class SelfieFragmentTest
    @Mock
	Context mContext;
    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        Mockito.doReturn(mContext).when(mContext).getApplicationContext();
        RxPermissions.getInstance(mContext);
        Mockito.doReturn(false).when(Mockito.spy(RxPermissions.getInstance(mContext))).isGranted(anyString());
        Mockito.doReturn(Observable.just(false)).when(Mockito.spy(RxPermissions.getInstance(mContext))).request(anyString());
    }
}  
```
I mocked the spy's isGranted() and request() to always return negatives but then when I request some permission it always returns positives (granted = true) and it goes to on the first branch where I do injection. I also set the sdk 23 in the testing class and in gradle but still no luck.

Thank you for any help  !

**Comment by tbruyelle** [comment]
Because you can't mock static method with mockito, I suggest you to declare a method like that in your activity : 

```java
public RxPermissions rxPermissions() {
  return RxPermission.getInstance(this);
}
```

Use this method everywhere you need RxPermissions and then in your test you can simply mock like that : 

```java
RxPermissions rxPermissions = mock(RxPermissions.class);
when(activity.rxPermissions).thenReturn(rxPermissions);
when(rxPermissions.request(anything()).thenReturn(Observable.just(true))
```

HTH

**Comment by PopTudor** [comment]
I forgot that info about not being able to mock static methods even though was obvious that it's not mocked when followed with the debugger so thanks for reminding me !
I was hoping I can just send true/false through direct access to the singleton but this way is better since now it doesn't depend on the internals of RxPermissions so thanks again and good luck !
