### ISSUE TITLE
Make RxPermissions.request return Single<Boolean>

### ISSUE THREAD

**Issue by PaulWoitaschek** [tbruyelle/RxPermissions#65]
As `request` only emits a single value, the correct representation is `Single<Boolean>`

**Comment by tbruyelle** [comment]
Nice one, but that's a breaking change (I think `Single` didn't exist when the lib was created).
I will keep that in my mind thanks.

**Comment by dkhmelenko** [comment]
@PaulWoitaschek `Single` and `Completable` are still in Beta.
Also, as @tbruyelle suggested those changes can break compatibility, because they do not implement `Observable`.

**Comment by tbruyelle** [comment]
The change will come with RxJava2 (see #71)
