### ISSUE TITLE
Detect when permissions was denied completely

### ISSUE THREAD

**Issue by votruk** [tbruyelle/RxPermissions#66]
I am wondering, is it possible to catch the case when user denied permission earlier with "Never show again" checked?

PS You have a great lib, it's very helpful! Thanks!

**Comment by tarasantoshchuk** [comment]
if you get **false** in onNext() (permission was denied) you can call 

`ActivityCompat.shouldShowRequestPermissionRationale(activity, permission);`

if it returns false - permission was denied with "Never show again" checked.

**Comment by votruk** [comment]
@tarasantoshchuk nice! Thank you!

**Comment by tbruyelle** [comment]
There's also `RxPermissions.shouldShowRequestPermissionRationale()` if you need to stay in the rx world.
