### ISSUE TITLE
Runtime Permission Denied

### ISSUE THREAD

**Issue by Malikkhoja** [tbruyelle/RxPermissions#67]
Hi,

If user has granted a specific permission to the app and while the application is running, user goes and revoke the permission from settings and just launch the app from the recent applications, Android OS by default restarts the activity and this is making my application crash or showing weird behavior. Does this library cover this issue? Please help.

**Comment by tarasantoshchuk** [comment]
> and this is making my application crash

Can you provide stack trace?

**Comment by tarasantoshchuk** [comment]
@Malikkhoja any updates?
