### ISSUE TITLE
Different error codes for denied permissions.

### ISSUE THREAD

**Issue by ramanbranavitski** [tbruyelle/RxPermissions#68]
It would be great if you add different resultCode when user denied permission with checked "Do not ask again" or not.

**Comment by tarasantoshchuk** [comment]
this would be convenient for library users

@tbruyelle 
What do you think about this?

**Comment by tbruyelle** [comment]
I think that's a good idea.

We could add an extra field to the `Permission` object to handle that.

**Comment by ramanbranavitski** [comment]
Hi there, how much time you need to implement this feature?

**Comment by tbruyelle** [comment]
will be release in 0.8.0
