### ISSUE TITLE
Code inside granted doesn't executed for the second time

### ISSUE THREAD

**Issue by ShivamDev31** [tbruyelle/RxPermissions#72]
Hi,

I've created a method which uses Smart location lib to get the user location.
Now I'm calling that method inside RxPermissions  subscriber--> granted. So for the first time it asks for the permission and works fine but when the user comes again and permission is already granted then it skips that block and that code never gets executed.
Any callback that the user has selected "Never" for the permission.

Here is some code:

RxPermissions.getInstance(this).request(Manifest.permission.ACCESS_FINE_LOCATION)
                .subscribe(granted -> {
                    if (granted) {
                        getUserLocation();
                    } else {
                        Logger.snackBar(findViewById(android.R.id.content), "Permission Denied");
                    }
                });

getUserLocation() is the one where permission is required. This method is executed only for the first time when I allow and never called second time as it never goes inside if else.

Moreover do you have any methods (like other locations libs does) where on deny we show a dialog of snackbar message with Settings link so enable it from there.
Actually I'm new with permissions so looking out for some support.

And is there anyway that once the user denies and we show him a dialog with explanation for the permission and if he clicks "Ok" show him the permission dialog again.

**Comment by tbruyelle** [comment]
Could you post more code plz ? The problem you have goes against the basic behavior of the library so I suspect there's something wrong in your code.

**Comment by ShivamDev31** [comment]
So this is the gist of my class : https://gist.github.com/ShivamDev31/1144a06fce8dd19fe2ecc29cdac7271e

If I keep line 55 commented then once the user allowed for permission and comes for the second time it wont get executed. For me it seems like 
RxPermissions.getInstance(this).request(Manifest.permission.ACCESS_FINE_LOCATION)
.subscribe(granted -> {

this checks if granted then skips the block as the code in if (granted) doesn't gets executed for the second time.

**Comment by tbruyelle** [comment]
I don't see any RxPermissions code in your gist.

**Comment by ShivamDev31** [comment]
Oops I think something got messed up there. I'll make a new gist once I got back home, will update it here. Thanks for prompt reply.

**Comment by ShivamDev31** [comment]
So this is the updated [code gist](https://gist.github.com/ShivamDev31/f5941abe0c036e90663fefaf316f4a89)

I've made a util method now to handle permissions. But it crashes sometimes giving permission error only.
Moreover while the permission box is there is shows the 'else' case snackbar too "Permission Denied".

Please let me know if I'm doing something wrong, or my implementation is wrong or something as its not working everytime. Sometime it the Log on even allowing it give false (CommonUtils log) and after that screen overlay detected go to settings. Strange behavior is happening.  

Also I would like to know once the user has granted the permission still the code under 'if' at 25 will be executed everytime?

**Comment by tbruyelle** [comment]
Your code in `CommonUtils` about RxPermissions is completely wrong, you need to learn more about asynchronous programming and how RxJava works.
Look at the code in the sample app and follow it.

I close the issue because it's not related to RxPermissions.

**Comment by tbruyelle** [comment]
And good luck :)

**Comment by ShivamDev31** [comment]
Everyone is in their learning phase, can you atleast tell me what I'm doing wrong there?

**Comment by ShivamDev31** [comment]
I've been working with rxjava for few months now. Atleast redirect me to an article where I can see what I'm doing wrong?

**Comment by tbruyelle** [comment]
I redirected you to the sample app, do the same and it will work.

Sorry I don't have the time to explain.
