### ISSUE TITLE
Using lambda expressions 

### ISSUE THREAD

**Issue by dkhmelenko** [tbruyelle/RxPermissions#73]
Because of Android Nougat was released and now it supports some of the features from Java 8. Does it make any sense to use Lambda expressions support?

**Comment by tbruyelle** [comment]
I think Nougat is not enough to enable Java 8 features, Jack compiler must also enabled as well.

**Comment by gengjiawen** [comment]
Retrolamda also works fine with Repermissions. Already using it.
