### ISSUE TITLE
Android N issue

### ISSUE THREAD

**Issue by daniel-sync** [tbruyelle/RxPermissions#81]
Hi there, I'm experiencing an issue with the library under Android N. 

It goes to the not granted block of code straight away without prompting the popup asking for the permission.

**Comment by tarasantoshchuk** [comment]
which permission are you requesting?

**Comment by daniel-sync** [comment]
I've tried with Manifest.permission.ACCESS_COARSE_LOCATION in one place and Manifest.permission.CAMERA in another, both of them are throwing the code I've put when it's not granted without prompting the popup.

**Comment by tarasantoshchuk** [comment]
have you tried to run the same code on Android M?
can you post your code here?

**Comment by daniel-sync** [comment]
I've found what the issue is, apparently the uses-permission had maxSdk to 23 and it was preventing it to behave correctly. My bad, sorry for the inconvenience. You can close this issue and great work with the library!
