### ISSUE TITLE
Observe permissions without requesting they be granted?

### ISSUE THREAD

**Issue by ZakTaccardi** [tbruyelle/RxPermissions#83]
I'd like to observe a permission, without forcing the dialog to pop up.

Is this possible?

**Comment by tbruyelle** [comment]
There is `RxPermissions.isGranted` method that calls internally`ContextCompat.checkSelfPermission` but it doesn't return an `Observable`, so you have to do it yourself.

```java
Observable.just(RxPermissions.isGranted(...))
```

**Comment by ZakTaccardi** [comment]
Sorry - I should have specified that I was looking for a hot observable, that would emit when it subscribes initially and when a permission changes.

This should be doable as long as long as the request is made through your `RxPermissions.request` API, where events can be forwarded to the hot observable by sharing some state.

**Comment by tbruyelle** [comment]
Ok I see. What's the benefit of such feature ?

**Comment by ZakTaccardi** [comment]
I have an `AudioJackDevice` that can have `open()` or `close()` called on it based on the microphone permission. Calling `open()` when permission is not granted would throw an exception. I would like to observe the microphone permission stream and combine it with an intent received from a microphone broadcast receiver. Here's a small kotlin excerpt:

```
Observable.combineLatest(intentObservable, permissionIsGrantedObservable) { intent, isGranted ->  AudioJackIntentInterpreter(intent, isGranted)})
                .map { interpreter -> if (interpreter.shouldOpen) device.open() else device.close}
```

**Comment by tbruyelle** [comment]
I don't see how the permission could be revoked at runtime. When you revoke a permission for an app in the settings, the app is killed by the framework.

**Comment by ZakTaccardi** [comment]
You're right. But I mostly care about the use case when it goes from not
granted to granted, and I want that part to be independent on the UI. Your
existing request API is dependent on the UI (because initializing in an
activity lifecycle method is a requirement). This poses a problem when I
want to observe (note, not request) a permission in my data layer, which is
outside the scope of the activity.

**Comment by tbruyelle** [comment]
By design, the process of permission request is hard-linked to the `Activity` (sadly like too much things in the Android framework). 

What you could try is sharing a subject between your activity and your data layer, observe that subject in the data layer and feed it in the activity when a permission is granted. Not sure if it's possible that said, I don't know your achitecture.

**Comment by tbruyelle** [comment]
And sharing a subject is probably over-engineering.
