### ISSUE TITLE
top flash?

### ISSUE THREAD

**Issue by dreamlivemeng** [tbruyelle/RxPermissions#85]
When I click “Never ask again”, and then click the button again, there will be a shadow of the top flash, this is how is it? Testing machine：Nexus 6P.

**Comment by tbruyelle** [comment]
Please join a screenshot, I don't understand.

**Comment by dreamlivemeng** [comment]
![image](https://cloud.githubusercontent.com/assets/18185775/19726580/2f5acfaa-9bbe-11e6-9bae-b65dffff2656.png)
、Hi, I'm sorry, my reply has been some late. When a permission is requested, a shadow flashes quickly at the toolbar.

**Comment by tbruyelle** [comment]
Should be fixed since we don't use an activity any more for requesting permission.
