### ISSUE TITLE
I can not call method "subscribe"

### ISSUE THREAD

**Issue by sinhpn92** [tbruyelle/RxPermissions#88]
My gradle import lib: `compile 'com.tbruyelle.rxpermissions:rxpermissions:0.8.0@aar'`
I can not call subsribe with rxPermission:
`RxPermissions rxPermissions = RxPermissions.getInstance(this);
        rxPermissions.request(Manifest.permission.CAMERA);`
How can i resolve this problem?

**Comment by AriaWang** [comment]
got  the same question  and   sovled.    
0.8.0   needs  rxjava  1.x version,  while  0.8.1  needs  rxjava   2.x version.

**Comment by tbruyelle** [comment]
> 0.8.0 needs rxjava 1.x version, while 0.8.1 needs rxjava 2.x version.

Not really. RxJava version is handled by the package name.
for RxJava 1.x use `compile 'com.tbruyelle.rxpermissions:rxpermissions:0.8.0@aar'`
for RxJava 2.x `compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.8.1@aar'`

**Comment by sinhpn92** [comment]
I tried with `rxpermissions` and `rxpermissions2`. But I can not found `subscribe` method. I tried restart and rebuild project on android studio, too.

**Comment by tbruyelle** [comment]
`rxPermissions.request(Manifest.permission.CAMERA).subscribe()` compiles.

**Comment by ThanosFisherman** [comment]
I'm having the same issue both with RxJava 1 and 2. After Rebuilding the project I got the following error
`error: cannot access Observable
class file for rx.Observable not found`
I guess I need to include the rxJava itself as a dependency?

**Comment by tbruyelle** [comment]
> I guess I need to include the rxJava itself as a dependency?

No, that's not required, Gradle do it for you. Package changes between RxJava1 and RxJava2, that's probably why you get this error.

**Comment by ThanosFisherman** [comment]
>  No, that's not required, Gradle do it for you.

I guess it should but there was no subscribe methods in neither of the two package names of the lib.
After adding the following manually
```
compile 'io.reactivex:rxjava:1.2.1'
compile 'com.tbruyelle.rxpermissions:rxpermissions:0.8.0@aar'
```
![nosubscribe](https://cloud.githubusercontent.com/assets/4888330/19960331/d26de5b4-a1b4-11e6-9c10-f104390d3bc5.JPG)

It worked as expected

**Comment by NeilSayok** [comment]
add this line to your gradel file implementation 'io.reactivex.rxjava2:rxjava:2.1.16'
