### ISSUE TITLE
`Never Ask Again` case for a single permission request

### ISSUE THREAD

**Issue by AAverin** [tbruyelle/RxPermissions#93]
I am asking for a single permission
```
rxPermissions.request(Manifest.permission.ACCESS_FINE_LOCATION)
```
this will return Observable<Boolean> with either granted or not.

How can I get when user selects "Never ask again" for a permission?

**Comment by AAverin** [comment]
SO far managed with
`Observable.just(true).compose(rxPermissions.ensureEach(Manifest.permission.ACCESS_FINE_LOCATION)).subscribe()`
Is it the right way?

**Comment by tbruyelle** [comment]
You can use `requestEach` which emits similar results but returns an observable rather than a transformer. See the readme just before the *Important read* section.
