### ISSUE TITLE
Compilation issues with RxJava 1.2.1

### ISSUE THREAD

**Issue by thekalinga** [tbruyelle/RxPermissions#95]
RxJava 1.2.2 seems to have deleted `AsyncEmitter` (which was deprecated sometime back), which is causing the build to fail.

Can you fix this please.

**Comment by tbruyelle** [comment]
I updated to 1.2.2 and so far so good c8e57f063785202d033f4ae47e833bfcc4c80a84

**Comment by tbruyelle** [comment]
I've just uploaded version 0.8.2 with rxJava 1.2.2 dependency if you want to check
