### ISSUE TITLE
when Manually disable permissions,the permission.granted return true.

### ISSUE THREAD

**Issue by onlybeyond** [tbruyelle/RxPermissions#97]
when Manually disable permissions,the permission.granted return true. (Android 5.0)

**Comment by epool** [comment]
@onlybeyond How do you disable permissions manually on Android 5.0? That feature was introduced on Android 6.0+ api 23 marshmallow. In previous version the permissions are accepted on installation time, but as far as I know there is not a way to disable them manually. If I'm wrong please share us a screenshot of how you are disabling the permissions manually and another one with the android version please.

**Comment by tbruyelle** [comment]
Closed no response from op
