### ISSUE TITLE
noHistory activity manifest closes app and leaves request dialog on screen

### ISSUE THREAD

**Issue by ersin-ertan** [tbruyelle/RxPermissions#99]
`MyActivity.class`
``` java
    RxPermissions rx = new RxPermissions(this);

    rx.request(Manifest.permission.READ_EXTERNAL_STORAGE).subscribe(aBoolean -> {
      Log.e(" ", String.valueOf(aBoolean));
    }, throwable -> Log.e(" ", throwable.getMessage()),
        () -> {
    });
```
`RxPermissionsFragment.class`
``` java
    @TargetApi(Build.VERSION_CODES.M)
    void requestPermissions(@NonNull String[] permissions) {
        requestPermissions(permissions, PERMISSIONS_REQUEST_CODE);
    }
``` 

Using the standard implementation of the 0.9.0, I call the above code in OnCreate. When debugging, upon starting requestPermissions() method, the app closes(not a ANR), leaving only the Permissions dialog box on the screen.

![screen shot 2016-11-21 at 3 29 13 pm](https://cloud.githubusercontent.com/assets/4809853/20475785/f50c19ca-afff-11e6-9d90-06280d014137.png)

**Comment by tbruyelle** [comment]
You have the problem only when debugging?

**Comment by ersin-ertan** [comment]
Sorry for the confusion, this problem occurs during both run and debug.

I wanted to emphasize that I have debugged to the point prior to when the app closes.

**Comment by tbruyelle** [comment]
When you request the permission, `onPause` is executed in your activity, do you execute specific code in there?

**Comment by ersin-ertan** [comment]
`MyActivity` extends from `BaseActivity`, which extends from `AppCompatActivity`

`MyActivity` only overrides `onBackPressed` and `onCreate`

The `rx.request` is located in `onCreate` and is the last thing called.

`MyActivity` does not override `onPaused`, nor does `BaseActivity`

`BaseActivity` only overrides `attachBaseContext` using `    super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));`

**Comment by tbruyelle** [comment]
Ok, @epool do you think it could come from the fragment ?

@ersin-ertan Can you check if you have a similar behavior with version 0.8.2 please ? You'll have to change `new RxPermissions(this)` with `RxPermissions.getInstance(this)`.

**Comment by ersin-ertan** [comment]
I can verify that this error occurs in both versions, 0.8.2 and 0.9.0, however:

the problem is `noHistory="true"`
``` xml
    <activity
        android:noHistory="true"
```

When set to false, this problem does not occur.

**Comment by tbruyelle** [comment]
Fine, so problem solved ?

**Comment by ersin-ertan** [comment]
I wouldn't think so, but I'm not sure what you as a library developer could do to prevent this problem. 

Having the noHistory option is important for some apps, would you know of any possible solutions?

**Comment by tbruyelle** [comment]
> I wouldn't think so, but I'm not sure what you as a library developer could do to prevent this problem.

Yes what I mean by 'problem solved'

> Having the noHistory option is important for some apps, would you know of any possible solutions?

No idea but I found this on stack : 
http://stackoverflow.com/questions/35151233/requesting-android-m-permissions-from-activity-with-nohistory-true-and-or-show?rq=1

**Comment by epool** [comment]
I just could reproduce this putting a breakpoint on `requestPermissions(permissions, PERMISSIONS_REQUEST_CODE);` from `RxPermissionsFragment`:
```java
@TargetApi(Build.VERSION_CODES.M)
void requestPermissions(@NonNull String[] permissions) {
    requestPermissions(permissions, PERMISSIONS_REQUEST_CODE);
}
```
When the breakpoint is reached(the permission dialog is not displayed yet), then I re-run the app on debug mode and there is where the dialog is shown. I couldn't find another way to reproduce this, so I'm not sure if it's a bug or something related with the app relaunching stuff.

But looks like it's not related with `android:noHistory="true|false"` that didn't affect my test flow.
